---
title: "Boxplots"
author: "Valerie Odeh"
date: "2023-09-20"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

library(ggplot2)
library(readxl)
library(magrittr)
library(dplyr)
library(gridExtra)
library(scales)
library(tidyverse)
library(ggsci)

# Results
#set working directory
file=setwd("/Users/valerieodeh/OneDrive - UW-Madison/R codes")

getwd()

read_excel_allsheets <- function(filename, tibble = FALSE) {
    # I prefer straight data.frames
    # but if you like tidyverse tibbles (the default with read_excel)
    # then just pass tibble = TRUE
    sheets <- readxl::excel_sheets(filename)
    x <- lapply(sheets, function(X) readxl::read_excel(filename, sheet = X))
    if(!tibble) x <- lapply(x, as.data.frame)
    names(x) <- sheets
    x
}
```

#Recalibration s=0
```{r}
rec.p.5s0_1 <- read_excel_allsheets("rec.p.5s0_run1.xlsx")
rec.p.5s0_2 <- read_excel_allsheets("rec.p.5s0_run2.xlsx")
rec.p.5s0_3 <- read_excel_allsheets("rec.p.5s0_run3.xlsx")
rec.p.5s0_4 <- read_excel_allsheets("rec.p.5s0_run4.xlsx")
rec.p.5s0_5 <- read_excel_allsheets("rec.p.5s0_run5.xlsx")
rec.p.5s0_6 <- read_excel_allsheets("rec.p.5s0_run6.xlsx")
rec.p.5s0_7 <- read_excel_allsheets("rec.p.5s0_run7.xlsx")
rec.p.5s0_8 <- read_excel_allsheets("rec.p.5s0_run8.xlsx")
rec.p.5s0_9 <- read_excel_allsheets("rec.p.5s0_run9.xlsx")
rec.p.5s0_10 <- read_excel_allsheets("rec.p.5s0_run10.xlsx")

#join 2000 reps
rec.p.5s0 <-  Map(rbind, rec.p.5s0_1, rec.p.5s0_2, rec.p.5s0_3, rec.p.5s0_4, rec.p.5s0_5, rec.p.5s0_6, rec.p.5s0_7, rec.p.5s0_8, rec.p.5s0_9, rec.p.5s0_10)

#remove from environment individual excels
rm(rec.p.5s0_1)
rm(rec.p.5s0_2)
rm(rec.p.5s0_3)
rm(rec.p.5s0_4)
rm(rec.p.5s0_5)
rm(rec.p.5s0_6)
rm(rec.p.5s0_7)
rm(rec.p.5s0_8)
rm(rec.p.5s0_9)
rm(rec.p.5s0_10)

```

```{r}
#rec.p.5s0 <- lapply(rec.p.5s0, function(df) subset(df,  df$Error > -20 & df$Error < 20 ))


rec.s0.r<- data.frame(t(sapply(rec.p.5s0, function(df) {
n <- mean(df$n, na.rm = TRUE)
Error <- mean(df$Error, na.rm = TRUE)
Var <- var(df$EST, na.rm = TRUE)
MSE <- mean(df$Error, na.rm=TRUE)^2+var(df$EST, na.rm = TRUE)
Coverage <- mean(df$Coverage, na.rm = TRUE)


return(c(n, Error, Var, MSE, Coverage))
}))) 


colnames(rec.s0.r) <- c("n","Bias", "Variance", "MSE", "Coverage")

```


```{r}
#identify parameters for ggplot
rec.p.5s0[[1]]$i <- 1500
rec.p.5s0[[2]]$i <- 2500
rec.p.5s0[[3]]$i <- 3500
rec.p.5s0[[4]]$i <- 1500
rec.p.5s0[[5]]$i <- 2500
rec.p.5s0[[6]]$i <- 3500
rec.p.5s0[[7]]$i <- 1500
rec.p.5s0[[8]]$i <- 2500
rec.p.5s0[[9]]$i <- 3500

rec.p.5s0[[1]]$r <- 0.5
rec.p.5s0[[2]]$r <- 0.5
rec.p.5s0[[3]]$r <- 0.5
rec.p.5s0[[4]]$r <- 1
rec.p.5s0[[5]]$r <- 1
rec.p.5s0[[6]]$r <- 1
rec.p.5s0[[7]]$r <- 1.5
rec.p.5s0[[8]]$r <- 1.5
rec.p.5s0[[9]]$r <- 1.5

rec.p.5s0[[1]]$model <- "Static"
rec.p.5s0[[2]]$model <- "Static"
rec.p.5s0[[3]]$model <- "Static"
rec.p.5s0[[4]]$model <- "Static"
rec.p.5s0[[5]]$model <- "Static"
rec.p.5s0[[6]]$model <- "Static"
rec.p.5s0[[7]]$model <- "Static"
rec.p.5s0[[8]]$model <- "Static"
rec.p.5s0[[9]]$model <- "Static"

#join dataset for ggplot
rec.p.5s0 <- do.call("rbind", rec.p.5s0)
rec.p.5s0$i <- as.factor(rec.p.5s0$i)
rec.p.5s0$r <- as.factor(rec.p.5s0$r)

```


#Boxplot

```{r}
library(ggplot2)
library(ggsci)

bp <- ggplot(rec.p.5s0, aes(x=r, y=Error, group=r)) + 
  geom_boxplot(aes(fill=r)) + facet_grid(model~i) +scale_y_continuous() + coord_flip() + theme_linedraw() +  scale_color_lancet() + theme(legend.position="none")+ geom_hline(yintercept = 0, color="red")
bp
```

#Recalibration s=1
```{r}
rec.p.5s1_1 <- read_excel_allsheets("rec.p.5s1_run1.xlsx")
rec.p.5s1_2 <- read_excel_allsheets("rec.p.5s1_run2.xlsx")
rec.p.5s1_3 <- read_excel_allsheets("rec.p.5s1_run3.xlsx")
rec.p.5s1_4 <- read_excel_allsheets("rec.p.5s1_run4.xlsx")
rec.p.5s1_5 <- read_excel_allsheets("rec.p.5s1_run5.xlsx")
rec.p.5s1_6 <- read_excel_allsheets("rec.p.5s1_run6.xlsx")
rec.p.5s1_7 <- read_excel_allsheets("rec.p.5s1_run7.xlsx")
rec.p.5s1_8 <- read_excel_allsheets("rec.p.5s1_run8.xlsx")
rec.p.5s1_9 <- read_excel_allsheets("rec.p.5s1_run9.xlsx")
rec.p.5s1_10 <- read_excel_allsheets("rec.p.5s1_run10.xlsx")

#join 2000 reps
rec.p.5s1 <-  Map(rbind, rec.p.5s1_1, rec.p.5s1_2, rec.p.5s1_3, rec.p.5s1_4, rec.p.5s1_5, rec.p.5s1_6, rec.p.5s1_7, rec.p.5s1_8, rec.p.5s1_9, rec.p.5s1_10)

#remove from environment individual excels
rm(rec.p.5s1_1)
rm(rec.p.5s1_2)
rm(rec.p.5s1_3)
rm(rec.p.5s1_4)
rm(rec.p.5s1_5)
rm(rec.p.5s1_6)
rm(rec.p.5s1_7)
rm(rec.p.5s1_8)
rm(rec.p.5s1_9)
rm(rec.p.5s1_10)
```

```{r}
#rec.p.5s1 <- lapply(rec.p.5s1, function(df) subset(df,  df$Error > -20 & df$Error < 20 ))

rec.s1.r<- data.frame(t(sapply(rec.p.5s1, function(df) {
n <- mean(df$n, na.rm = TRUE)
Error <- mean(df$Error, na.rm = TRUE)
Var <- var(df$EST, na.rm = TRUE)
MSE <- mean(df$Error, na.rm=TRUE)^2+var(df$EST, na.rm = TRUE)
Coverage <- mean(df$Coverage, na.rm = TRUE)

return(c(n, Error, Var, MSE, Coverage))
}))) 


colnames(rec.s1.r) <- c("n","Bias", "Variance", "MSE", "Coverage")

```

```{r}
#identify parameters for ggplot
rec.p.5s1[[1]]$i <- 1500
rec.p.5s1[[2]]$i <- 2500
rec.p.5s1[[3]]$i <- 3500
rec.p.5s1[[4]]$i <- 1500
rec.p.5s1[[5]]$i <- 2500
rec.p.5s1[[6]]$i <- 3500
rec.p.5s1[[7]]$i <- 1500
rec.p.5s1[[8]]$i <- 2500
rec.p.5s1[[9]]$i <- 3500

rec.p.5s1[[1]]$r <- 0.5
rec.p.5s1[[2]]$r <- 0.5
rec.p.5s1[[3]]$r <- 0.5
rec.p.5s1[[4]]$r <- 1
rec.p.5s1[[5]]$r <- 1
rec.p.5s1[[6]]$r <- 1
rec.p.5s1[[7]]$r <- 1.5
rec.p.5s1[[8]]$r <- 1.5
rec.p.5s1[[9]]$r <- 1.5

rec.p.5s1[[1]]$model <- "Recalibration (s=1)"
rec.p.5s1[[2]]$model <- "Recalibration (s=1)"
rec.p.5s1[[3]]$model <- "Recalibration (s=1)"
rec.p.5s1[[4]]$model <- "Recalibration (s=1)"
rec.p.5s1[[5]]$model <- "Recalibration (s=1)"
rec.p.5s1[[6]]$model <- "Recalibration (s=1)"
rec.p.5s1[[7]]$model <- "Recalibration (s=1)"
rec.p.5s1[[8]]$model <- "Recalibration (s=1)"
rec.p.5s1[[9]]$model <- "Recalibration (s=1)"

#join dataset for ggplot
rec.p.5s1 <- do.call("rbind", rec.p.5s1)
rec.p.5s1$i <- as.factor(rec.p.5s1$i)
rec.p.5s1$r <- as.factor(rec.p.5s1$r)

```

```{r}
library(ggplot2)
library(ggsci)

bp <- ggplot(rec.p.5s1, aes(x=r, y=Error, group=r)) + 
  geom_boxplot(aes(fill=r)) + facet_grid(model~i) +scale_y_continuous() + coord_flip() + theme_linedraw() +  scale_color_lancet() + theme(legend.position="none")+ geom_hline(yintercept = 0, color="red")
bp
```


#Revision s=.5
```{r}
rev.p.5s.5_1 <- read_excel_allsheets("rev.p.5s.5_run1.xlsx")
rev.p.5s.5_2 <- read_excel_allsheets("rev.p.5s.5_run2.xlsx")
rev.p.5s.5_3 <- read_excel_allsheets("rev.p.5s.5_run3.xlsx")
rev.p.5s.5_4 <- read_excel_allsheets("rev.p.5s.5_run4.xlsx")
rev.p.5s.5_5 <- read_excel_allsheets("rev.p.5s.5_run5.xlsx")
rev.p.5s.5_6 <- read_excel_allsheets("rev.p.5s.5_run6.xlsx")
rev.p.5s.5_7 <- read_excel_allsheets("rev.p.5s.5_run7.xlsx")
rev.p.5s.5_8 <- read_excel_allsheets("rev.p.5s.5_run8.xlsx")
rev.p.5s.5_9 <- read_excel_allsheets("rev.p.5s.5_run9.xlsx")
rev.p.5s.5_10 <- read_excel_allsheets("rev.p.5s.5_run10.xlsx")

#join 2500 reps
rev.p.5s.5 <-  Map(rbind, rev.p.5s.5_1, rev.p.5s.5_2, rev.p.5s.5_3, rev.p.5s.5_4, rev.p.5s.5_5, rev.p.5s.5_6, rev.p.5s.5_7, rev.p.5s.5_8, rev.p.5s.5_9, rev.p.5s.5_10)

#remove from environment individual excels
rm(rev.p.5s.5_1)
rm(rev.p.5s.5_2)
rm(rev.p.5s.5_3)
rm(rev.p.5s.5_4)
rm(rev.p.5s.5_5)
rm(rev.p.5s.5_6)
rm(rev.p.5s.5_7)
rm(rev.p.5s.5_8)
rm(rev.p.5s.5_9)
rm(rev.p.5s.5_10)
```

```{r}
rev.p.5s.5 <- lapply(rev.p.5s.5, function(df) subset(df,  df$Error > -15 & df$Error < 15 ))

rev.s.5.r<- data.frame(t(sapply(rev.p.5s.5, function(df) {
n <- mean(df$n, na.rm = TRUE)
Error <- mean(df$Error, na.rm = TRUE)
Var <- var(df$EST, na.rm = TRUE)
MSE <- mean(df$Error, na.rm=TRUE)^2+var(df$EST, na.rm = TRUE)
Coverage <- mean(df$Coverage, na.rm = TRUE)

return(c(n, Error, Var, MSE, Coverage))
}))) 


colnames(rev.s.5.r) <- c("n", "Bias", "Variance", "MSE", "Coverage")

```

```{r}
#identify parameters for ggplot
rev.p.5s.5[[1]]$i <- 1500
rev.p.5s.5[[2]]$i <- 2500
rev.p.5s.5[[3]]$i <- 3500
rev.p.5s.5[[4]]$i <- 1500
rev.p.5s.5[[5]]$i <- 2500
rev.p.5s.5[[6]]$i <- 3500
rev.p.5s.5[[7]]$i <- 1500
rev.p.5s.5[[8]]$i <- 2500
rev.p.5s.5[[9]]$i <- 3500

rev.p.5s.5[[1]]$r <- 0.5
rev.p.5s.5[[2]]$r <- 0.5
rev.p.5s.5[[3]]$r <- 0.5
rev.p.5s.5[[4]]$r <- 1
rev.p.5s.5[[5]]$r <- 1
rev.p.5s.5[[6]]$r <- 1
rev.p.5s.5[[7]]$r <- 1.5
rev.p.5s.5[[8]]$r <- 1.5
rev.p.5s.5[[9]]$r <- 1.5

rev.p.5s.5[[1]]$model <- "Revision (s=0.5)"
rev.p.5s.5[[2]]$model <- "Revision (s=0.5)"
rev.p.5s.5[[3]]$model <- "Revision (s=0.5)"
rev.p.5s.5[[4]]$model <- "Revision (s=0.5)"
rev.p.5s.5[[5]]$model <- "Revision (s=0.5)"
rev.p.5s.5[[6]]$model <- "Revision (s=0.5)"
rev.p.5s.5[[7]]$model <- "Revision (s=0.5)"
rev.p.5s.5[[8]]$model <- "Revision (s=0.5)"
rev.p.5s.5[[9]]$model <- "Revision (s=0.5)"

#join dataset for ggplot
rev.p.5s.5 <- do.call("rbind", rev.p.5s.5)
rev.p.5s.5$i <- as.factor(rev.p.5s.5$i)
rev.p.5s.5$r <- as.factor(rev.p.5s.5$r)

```


```{r}
library(ggplot2)
library(ggsci)

bp <- ggplot(rev.p.5s.5, aes(x=r, y=Error, group=r)) + 
  geom_boxplot(aes(fill=r)) + facet_grid(model~i) +scale_y_continuous() + coord_flip() + theme_linedraw() +  scale_color_lancet() + theme(legend.position="none")+ geom_hline(yintercept = 0, color="red") +ylim(-5,5)
bp
```

#Recalibration s=0.5

```{r}
rec.p.5s.5_1 <- read_excel_allsheets("rec.p.5s.0.5_run1.xlsx")
rec.p.5s.5_2 <- read_excel_allsheets("rec.p.5s.0.5_run2.xlsx")
rec.p.5s.5_3 <- read_excel_allsheets("rec.p.5s.0.5_run3.xlsx")
rec.p.5s.5_4 <- read_excel_allsheets("rec.p.5s.0.5_run4.xlsx")
rec.p.5s.5_5 <- read_excel_allsheets("rec.p.5s.0.5_run5.xlsx")
rec.p.5s.5_6 <- read_excel_allsheets("rec.p.5s.0.5_run6.xlsx")
rec.p.5s.5_7 <- read_excel_allsheets("rec.p.5s.0.5_run7.xlsx")
rec.p.5s.5_8 <- read_excel_allsheets("rec.p.5s.0.5_run8.xlsx")
rec.p.5s.5_9 <- read_excel_allsheets("rec.p.5s.0.5_run9.xlsx")
rec.p.5s.5_10 <- read_excel_allsheets("rec.p.5s.0.5_run10.xlsx")

#join 2000 reps
rec.p.5s.5 <-  Map(rbind, rec.p.5s.5_1, rec.p.5s.5_2, rec.p.5s.5_3, rec.p.5s.5_4, rec.p.5s.5_5, rec.p.5s.5_6, rec.p.5s.5_7, rec.p.5s.5_8, rec.p.5s.5_9, rec.p.5s.5_10)

#remove from environment individual excels
rm(rec.p.5s.5_1)
rm(rec.p.5s.5_2)
rm(rec.p.5s.5_3)
rm(rec.p.5s.5_4)
rm(rec.p.5s.5_5)
rm(rec.p.5s.5_6)
rm(rec.p.5s.5_7)
rm(rec.p.5s.5_8)
rm(rec.p.5s.5_9)
rm(rec.p.5s.5_10)

```

```{r}
rec.p.5s.5 <- lapply(rec.p.5s.5, function(df) subset(df,  df$Error > -15 & df$Error < 15 ))

rec.s.5.r<- data.frame(t(sapply(rec.p.5s.5, function(df) {
n <- mean(df$n, na.rm = TRUE)
Error <- mean(df$Error, na.rm = TRUE)
Var <- var(df$EST, na.rm = TRUE)
MSE <- mean(df$Error, na.rm=TRUE)^2+var(df$EST, na.rm = TRUE)
Coverage <- mean(df$Coverage, na.rm = TRUE)

return(c(n, Error, Var, MSE, Coverage))
}))) 


colnames(rec.s.5.r) <- c("n", "Bias", "Variance", "MSE", "Coverage")

```


```{r}
#identify parameters for ggplot
rec.p.5s.5[[1]]$i <- 1500
rec.p.5s.5[[2]]$i <- 2500
rec.p.5s.5[[3]]$i <- 3500
rec.p.5s.5[[4]]$i <- 1500
rec.p.5s.5[[5]]$i <- 2500
rec.p.5s.5[[6]]$i <- 3500
rec.p.5s.5[[7]]$i <- 1500
rec.p.5s.5[[8]]$i <- 2500
rec.p.5s.5[[9]]$i <- 3500

rec.p.5s.5[[1]]$r <- 0.5
rec.p.5s.5[[2]]$r <- 0.5
rec.p.5s.5[[3]]$r <- 0.5
rec.p.5s.5[[4]]$r <- 1
rec.p.5s.5[[5]]$r <- 1
rec.p.5s.5[[6]]$r <- 1
rec.p.5s.5[[7]]$r <- 1.5
rec.p.5s.5[[8]]$r <- 1.5
rec.p.5s.5[[9]]$r <- 1.5

rec.p.5s.5[[1]]$model <- "Recalibration (s=0.5)"
rec.p.5s.5[[2]]$model <- "Recalibration (s=0.5)"
rec.p.5s.5[[3]]$model <- "Recalibration (s=0.5)"
rec.p.5s.5[[4]]$model <- "Recalibration (s=0.5)"
rec.p.5s.5[[5]]$model <- "Recalibration (s=0.5)"
rec.p.5s.5[[6]]$model <- "Recalibration (s=0.5)"
rec.p.5s.5[[7]]$model <- "Recalibration (s=0.5)"
rec.p.5s.5[[8]]$model <- "Recalibration (s=0.5)"
rec.p.5s.5[[9]]$model <- "Recalibration (s=0.5)"


#join dataset for ggplot
rec.p.5s.5 <- do.call("rbind", rec.p.5s.5)
rec.p.5s.5$i <- as.factor(rec.p.5s.5$i)
rec.p.5s.5$r <- as.factor(rec.p.5s.5$r)

```


#Boxplot

```{r}
library(ggplot2)
library(ggsci)

bp <- ggplot(rec.p.5s.5, aes(x=r, y=Error, group=r)) + 
  geom_boxplot(aes(fill=r)) + facet_grid(model~i) +scale_y_continuous() + coord_flip() + theme_linedraw() +  scale_color_lancet() + theme(legend.position="none")+ geom_hline(yintercept = 0, color="red")
bp
```


#Recalibration s=0 Weight scenario

```{r}
weight_1 <- read_excel_allsheets("rec.p.5s.0_wgtMErun1.xlsx")
weight_2 <- read_excel_allsheets("rec.p.5s.0_wgtMErun2.xlsx")
weight_3 <- read_excel_allsheets("rec.p.5s.0_wgtMErun3.xlsx")
weight_4 <- read_excel_allsheets("rec.p.5s.0_wgtMErun4.xlsx")
weight_5 <- read_excel_allsheets("rec.p.5s.0_wgtMErun5.xlsx")
weight_6 <- read_excel_allsheets("rec.p.5s.0_wgtMErun6.xlsx")
weight_7 <- read_excel_allsheets("rec.p.5s.0_wgtMErun7.xlsx")
weight_8 <- read_excel_allsheets("rec.p.5s.0_wgtMErun8.xlsx")
weight_9 <- read_excel_allsheets("rec.p.5s.0_wgtMErun9.xlsx")
weight_10 <- read_excel_allsheets("rec.p.5s.0_wgtMErun10.xlsx")
weight_11 <- read_excel_allsheets("rec.p.5s.0_wgtMErun11.xlsx")

#join 2000 reps
weight <-  Map(rbind, weight_1, weight_2, weight_3, weight_4, weight_5, weight_6, weight_7, weight_8, weight_9, weight_10, weight_11)

#remove from environment individual excels
rm(weight_1)
rm(weight_2)
rm(weight_3)
rm(weight_4)
rm(weight_5)
rm(weight_6)
rm(weight_7)
rm(weight_8)
rm(weight_9)
rm(weight_10)
rm(weight_11)

```

```{r}
#weight <- lapply(weight, function(df) subset(df,  df$Error > -20 & df$Error < 20 ))


weight.r<- data.frame(t(sapply(weight, function(df) {
n <- mean(df$n, na.rm = TRUE)
Error <- mean(df$Error, na.rm = TRUE)
Var <- var(df$EST, na.rm = TRUE)
MSE <- mean(df$Error, na.rm=TRUE)^2+var(df$EST, na.rm = TRUE)
Coverage <- mean(df$Coverage, na.rm = TRUE)

return(c(n, Error, Var, MSE, Coverage))
}))) 


colnames(weight.r) <- c("n", "Bias", "Variance", "MSE", "Coverage")

```


```{r}
#identify parameters for ggplot
weight[[1]]$i <- 1500
weight[[2]]$i <- 2500
weight[[3]]$i <- 3500
weight[[4]]$i <- 1500
weight[[5]]$i <- 2500
weight[[6]]$i <- 3500
weight[[7]]$i <- 1500
weight[[8]]$i <- 2500
weight[[9]]$i <- 3500

weight[[1]]$r <- 0.5
weight[[2]]$r <- 0.5
weight[[3]]$r <- 0.5
weight[[4]]$r <- 1
weight[[5]]$r <- 1
weight[[6]]$r <- 1
weight[[7]]$r <- 1.5
weight[[8]]$r <- 1.5
weight[[9]]$r <- 1.5

weight[[1]]$model <- "Static/Weight outcome"
weight[[2]]$model <- "Static/Weight outcome"
weight[[3]]$model <- "Static/Weight outcome"
weight[[4]]$model <- "Static/Weight outcome"
weight[[5]]$model <- "Static/Weight outcome"
weight[[6]]$model <- "Static/Weight outcome"
weight[[7]]$model <- "Static/Weight outcome"
weight[[8]]$model <- "Static/Weight outcome"
weight[[9]]$model <- "Static/Weight outcome"


#join dataset for ggplot
weight <- do.call("rbind", weight)
weight$i <- as.factor(weight$i)
weight$r <- as.factor(weight$r)

```


#Boxplot

```{r}
library(ggplot2)
library(ggsci)

bp <- ggplot(weight, aes(x=r, y=Error, group=r)) + 
  geom_boxplot(aes(fill=r)) + facet_grid(model~i) +scale_y_continuous() + coord_flip() + theme_linedraw() +  scale_color_lancet() + theme(legend.position="none")+ geom_hline(yintercept = 0, color="red")+ylim(-5,5)
bp
```



#Join results

```{r}

data <- data.frame(rbind(rec.p.5s0, rec.p.5s1,rec.p.5s.5, rev.p.5s.5, weight))
data$i <- as.factor(data$i)
data$r <- as.factor(data$r)

```


```{r}
library(ggplot2)
bp <- ggplot(data, aes(x=r, y=Error, group=r)) + 
  geom_boxplot(aes(fill=r)) + facet_grid(model~i, scales="free") +scale_y_continuous() + coord_flip() + theme_linedraw() +  scale_color_lancet() + theme(legend.position="none")+ geom_hline(yintercept = 0, color="red") 

bp

```

```{r}
data$model <- factor(data$model, levels=c("Static", "Recalibration (s=0.5)", "Recalibration (s=1)", "Revision (s=0.5)", "Static/Weight outcome"))

data$r <- factor(data$r, levels=c("1.5", "1", "0.5"))

library(ggplot2)
bp <- ggplot(subset(data, model != "Static/Weight outcome"), aes(x=r, y=Error, group=r))  + geom_boxplot(aes(fill=r), coef = Inf) + facet_grid(i~model, scales="free") +scale_y_continuous() + coord_flip() + theme_linedraw() +  scale_color_lancet() + theme(legend.position="none") + geom_hline(yintercept = 0, color="red") 

bp

```


```{r}
data$model <- factor(data$model, levels=c("Static", "Recalibration (s=0.5)", "Recalibration (s=1)", "Revision (s=0.5)", "Static/Weight outcome"))

data$r <- factor(data$r, levels=c("1.5", "1", "0.5"))

library(ggplot2)
bp <- ggplot(subset(data, model == "Static/Weight outcome"), aes(x=r, y=Error, group=r))  + geom_boxplot(aes(fill=r), coef = Inf) + facet_grid(i~model, scales="free") +scale_y_continuous() + coord_flip() + theme_linedraw() +  scale_color_lancet() + theme(legend.position="none") + geom_hline(yintercept = 0, color="red") 

bp

```







```{r}
library(ggplot2)
bp <- ggplot(data, aes(x=r, y=Error, group=r)) + 
  geom_boxplot(aes(fill=r), outlier.shape = NA) + facet_grid(model~i, scales="free") +scale_y_continuous()  + theme_linedraw() +  scale_color_lancet() + theme(legend.position="none")+ geom_hline(yintercept = 0, color="red") +ylim(-.8,.8)

bp

```



```{r}
library(ggplot2)
bp <- ggplot(data, aes(x=r, y=Error, group=r)) + 
  geom_boxplot(aes(fill=r)) + facet_wrap(model~i, scales="free") +scale_y_continuous() + coord_flip() + theme_linedraw() +  scale_color_lancet() + theme(legend.position="none")+ geom_hline(yintercept = 0, color="red") 


bp

```

```{r}
library(ggplot2)
bp <- ggplot(data, aes(x=r, y=Error, group=r)) + 
  geom_boxplot(aes(fill=r)) + facet_wrap(model~i, scales="free") +scale_y_continuous()  + theme_linedraw() +  scale_color_lancet() + theme(legend.position="none")+ geom_hline(yintercept = 0, color="red") 


bp

```

#Results Data
```{r}
rec.s.5.r$Model <- "Recalibration (s=0.5)"
rec.s0.r$Model <- "Static"
rec.s1.r$Model <- "Recalibration (s=1)"
rev.s.5.r$Model <- "Revision (s=0.5)"
weight.r$Model <- "Static/Weight outcome"

rec.s.5.r$r <- c(0.5, 0.5, 0.5, 1, 1, 1, 1.5, 1.5, 1.5)
rec.s0.r$r <- c(0.5, 0.5, 0.5, 1, 1, 1, 1.5, 1.5, 1.5)
rec.s1.r$r <- c(0.5, 0.5, 0.5, 1, 1, 1, 1.5, 1.5, 1.5)
rev.s.5.r$r <- c(0.5, 0.5, 0.5, 1, 1, 1, 1.5, 1.5, 1.5)
weight.r$r <- c(0.5, 0.5, 0.5, 1, 1, 1, 1.5, 1.5, 1.5)

rec.s.5.r$i <- c(1500, 2500, 3500,1500, 2500, 3500, 1500, 2500, 3500)
rec.s0.r$i <- c(1500, 2500, 3500,1500, 2500, 3500, 1500, 2500, 3500)
rec.s1.r$i <- c(1500, 2500, 3500,1500, 2500, 3500, 1500, 2500, 3500)
rev.s.5.r$i <- c(1500, 2500, 3500,1500, 2500, 3500, 1500, 2500, 3500)
weight.r$i <- c(1500, 2500, 3500,1500, 2500, 3500, 1500, 2500, 3500)

resdata <- data.frame(rbind(rec.s0.r, rec.s.5.r, rec.s1.r, rev.s.5.r, weight.r)) 

```

```{r}
openxlsx::write.xlsx(resdata, file = "/Users/valerieodeh/Library/CloudStorage/OneDrive-UW-Madison/R codes/resdata.xlsx", rowNames = FALSE)

```


#error bars plots


```{r}
#function
data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- rename(data_sum, c("mean" = varname))
 return(data_sum)
}
```


#summarize data
```{r}
dataest <- data_summary(data, varname="EST", groupnames=c("model","i","r"))
dataerror <- data_summary(data, varname="Error", groupnames=c("model","i","r"))
```

```{r}
openxlsx::write.xlsx(dataest, file = "/Users/valerieodeh/Library/CloudStorage/OneDrive-UW-Madison/R codes/estdata.xlsx", rowNames = FALSE)

```

#color-blind friendly palette
```{r}
# The palette with grey:
cbPalette <- c("#0072B2", "#D55E00", "#CC79A7","#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442")

# The palette with black:
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# To use for fills, add
  #scale_fill_manual(values=cbPalette)

```


#plot
```{r}
dataest$model <- factor(dataest$model, levels=c("Static", "Recalibration (s=0.5)", "Recalibration (s=1)", "Revision (s=0.5)", "Static/Weight outcome"))

dataest$r <- factor(dataest$r, levels=c( "1.5", "1", "0.5"))

p<- ggplot(subset(dataest, model != "Static/Weight outcome"), aes(x=r, y=EST, group=r, color=r)) + 
  geom_line() +
  geom_point()+
  geom_errorbar(aes(ymin=EST-sd, ymax=EST+sd), width=.2) + facet_grid(i~model) +scale_y_continuous() + coord_flip() + theme_linedraw()  + theme(legend.position="none")+ geom_hline(yintercept = -.2, color="black", linetype='dotted') + ylab("Local Average Treatment Effect") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + scale_colour_manual(values=cbPalette)
print(p)

ggsave(filename= "EST1.pdf", plot = last_plot(), path = "/Users/valerieodeh/Library/CloudStorage/OneDrive-UW-Madison/R codes", dpi = "screen")
```



#plot
```{r}
p<- ggplot(subset(dataest, model == "Static/Weight outcome"), aes(x=r, y=EST, group=r, color=r)) + 
  geom_line() +
  geom_point()+
  geom_errorbar(aes(ymin=EST-sd, ymax=EST+sd), width=.2) + facet_grid(model~i) +scale_y_continuous() + coord_flip() + theme_linedraw() +   theme(legend.position="none")+ geom_hline(yintercept = -5, color="black", linetype='dotted') + ylab("Local Average Treatment Effect")+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), aspect.ratio = 1) + scale_colour_manual(values=cbPalette) 
print(p)

ggsave(filename= "EST2.pdf", plot = last_plot(), path = "/Users/valerieodeh/Library/CloudStorage/OneDrive-UW-Madison/R codes", dpi = "screen")
```

```{r}
dataest$hline <- c(rep(-0.2,36), rep(-5, 9))
dataest$model <- factor(dataest$model, levels=c("Static", "Recalibration (s=0.5)", "Recalibration (s=1)", "Revision (s=0.5)", "Static/Weight outcome"))

dataest$r <- factor(dataest$r, levels=c( "1.5", "1", "0.5"))

p<- ggplot(dataest, aes(x=r, y=EST, group=r, color=r)) + 
  geom_line() +
  geom_point()+
  geom_errorbar(aes(ymin=EST-sd, ymax=EST+sd), width=.2) + facet_grid(i~model, scales="free") +scale_y_continuous() + coord_flip() + theme_linedraw()  + theme(legend.position="none")+ geom_hline(data = dataest, aes(yintercept = hline), color="black", linetype='dotted')+ ylab("Local Average Treatment Effect") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + scale_colour_manual(values=cbPalette)
print(p)

ggsave(filename= "EST3.pdf", plot = last_plot(), path = "/Users/valerieodeh/Library/CloudStorage/OneDrive-UW-Madison/R codes", dpi = "screen", scale=1.2)
```


#plot
```{r}
p<- ggplot(subset(dataerror, model != "Static/Weight outcome"), aes(x=r, y=Error, group=r, color=r)) + 
  geom_line() +
  geom_point()+
  geom_errorbar(aes(ymin=Error-sd, ymax=Error+sd), width=.2) + facet_grid(model~i, scales="free") +scale_y_continuous() + coord_flip() + theme_linedraw() +  scale_color_lancet() + theme(legend.position="none")+ geom_hline(yintercept = 0, color="red")
print(p)
```


