---
  title: "Cutoff_simulationreps"
author: "Valerie Odeh"
date: "2023-08-10"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

library(foreign)
library(tidyverse)
library(mice)
library(dplyr)
library(gee)
library(optimx)
library(future.apply)


# NHANES DATA 2017-2018
#set working directory
file=setwd("P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs")


getwd()

demo <- read.xport(file="DEMO_J.XPT")
bpx <- read.xport(file="BPX_J.XPT")
diq <- read.xport(file="DIQ_J.XPT")
bpq <- read.xport(file="BPQ_J.XPT")
hdl <- read.xport(file="HDL_J.XPT")
trigly <- read.xport(file="TRIGLY_J.XPT")
bmx <- read.xport(file="BMX_J.XPT")
glu <- read.xport(file="GLU_J.XPT")
```


```{r, include=FALSE}

#put all data frames into list
df_list <- list(demo, bpx, diq, bpq, hdl, trigly, bmx, glu)     

#merge all data frames together
NHANES <- df_list %>% reduce(full_join, by='SEQN')
#NHANES <- df_list %>% reduce(merge, by='SEQN', all=FALSE)

data <- NHANES[,c("RIDAGEYR", "RIAGENDR", "BPXSY1", "BPXDI1","BPQ050A", "LBXGLU", "LBDHDD", "LBXTR", "BMXBMI", "DIQ010", "DIQ175A")]

data <- subset(data, RIDAGEYR>=45 & RIDAGEYR<=65) #between 45 and 65 years old (middle aged)
data <- subset(data, DIQ010=="2") #no diab initially

#data cleaning

#gender #1=male(ref), 2=female ---> change to 1=male(ref), 0=female
data$RIAGENDR <- ifelse(data$RIAGENDR=="1",1,0)

#BP meds #1=yes(ref), 2=no ---> change to 1=yes(ref), 0=no
data$BPQ050A <- ifelse(data$BPQ050A=="1",1,0)

#diabetes family history #10=yes(ref) ---> change to 1=yes(ref), 0=no
data$DIQ175A<- ifelse(data$DIQ175A=="10",1,0)
data$DIQ175A[is.na(data$DIQ175A)] <- 0
#str(data)

#data imputation
set.seed(1)
imputed <- mice(data)
data <- complete(imputed)

# Standardized variables
data$sex.s <- as.numeric(scale(data$RIAGENDR))
data$hdiab.s <- as.numeric(scale(data$DIQ175A))
data$age.s <- as.numeric(scale(data$RIDAGEYR))
data$BMI.s <- as.numeric(scale(data$BMXBMI))
data$HDL.s <- as.numeric(scale(data$LBDHDD))
data$trig.s <- as.numeric(scale(data$LBXTR))
data$glu.s <- as.numeric(scale(data$LBXGLU))
data$bp1.s <- as.numeric(scale(data$BPXSY1))
data$bp2.s <- as.numeric(scale(data$BPXDI1))
data$bp3.s <- as.numeric(scale(data$BPQ050A))


# 7-year risk of diabetes type 2
#for risk calc:

#age categories
data$age1 <- ifelse(data$RIDAGEYR < 50, 1, 0)
data$age2 <- ifelse(data$RIDAGEYR >= 50 & data$RIDAGEYR < 65, 1, 0)
data$age3 <- ifelse(data$RIDAGEYR >= 65, 1, 0)
data$age <- ifelse(data$age1 == 1, 1, ifelse(data$age2 == 1, 2, 3)) #general cat for revision
data$age <- as.factor(data$age) #make age cat
#BMI categories
data$BMI1 <- ifelse(data$BMXBMI < 25, 1, 0)
data$BMI2 <- ifelse(data$BMXBMI >= 25 & data$BMXBMI < 30, 1, 0)
data$BMI3 <- ifelse(data$BMXBMI >= 30, 1, 0)
data$BMI <- ifelse(data$BMI1 == 1, 1, ifelse(data$BMI2 == 1, 2, 3)) #general cat for revision
data$BMI <- as.factor(data$BMI) #make BMI cat
#HDL categories
data$HDL <- ifelse((data$RIAGENDR == 1 & data$LBDHDD < 40) | (data$RIAGENDR == 0 & data$LBDHDD < 50), 1, 0)
#triglyceride
data$trig <- ifelse(data$LBXTR >= 150, 1, 0)
#fasting glucose
data$glucose <- ifelse(data$LBXGLU >= 100, 1, 0)
#blood pressure
data$bp <- ifelse(data$BPXSY1 >= 130 | data$BPXDI1 >=85 | data$BPQ050A == 1, 1, 0)

#linesearch of optimal cutoff value to reach 50% of treatment rate
#initialize
p <- .5
data$c <- .05


data$Zhat <- -5.517-0.018*data$age2-0.081*data$age3-0.010*data$RIAGENDR+0.565*data$DIQ175A+0.301*data$BMI2+0.92*data$BMI3+0.498*data$bp+0.944*data$HDL+0.575*data$trig+1.980*data$glucose

data$risk <- (1/(1+exp(-data$Zhat)))-data$c
data$A <- ifelse(data$risk>=0, 1, 0)

data$Zprob <- (1/(1+exp(-(0.5*data$Zhat+0.5))))-.2*data$A

set.seed(1)
data$Zreal <- rbinom(n=nrow(data), size = 1, prob = data$Zprob)



dataraw <- data

rm(demo)
rm(bpx)
rm(diq)
rm(bpq)
rm(hdl)
rm(trigly)
rm(bmx)
rm(glu)
rm(NHANES)
rm(imputed)
rm(df_list)
```



#Recal with cutoff p function:
```{r}
recalcutp <- function(reps=20, p =.5, s= 0) {
  
  datarecal <- list()
  for(k in 1:reps) {
    
    data <- dataraw[sample(c(1:nrow(dataraw)), size=3500, replace=TRUE),]
    
    
    data$id <- seq(1, nrow(data))
    
    
    for(i in 2:200) {
      
      data$c[i] <- max((sum(data$A[1:i-1])/data$id[i-1])-p, 0)
      data$risk[i] <- (1/(1+exp(-data$Zhat[i])))-data$c[i]
      data$A[i] <- ifelse(data$risk[i]>=0, 1, 0)
      data$Zprob[i] <- (1/(1+exp(-(0.5*data$Zhat[i]+0.5))))-.2*data$A[i]
      
      data$Zreal[i] <- rbinom(n=1, size = 1, prob = data$Zprob[i])
    }
    
    
    data$a <- 0
    data$b <- 0
    
    
    data$s <- s #static risk pred model
    
    
    data$Zhatup <- data$Zhat
    data$riskup <- data$risk
    data$Aup <- data$A
    data$Zprobup <- data$Zprob
    data$Zrealup <- data$Zreal
    
    
    #fit a log reg and update linear predictor
    for(i in 200:(nrow(data)-1)) {
      calibrate <- glm(Zrealup~Zhatup, family = "binomial", data = data[1:i,], subset = Aup==0)
      data$a[i+1] <- calibrate$coefficients[[1]]
      data$b[i+1] <- calibrate$coefficients[[2]]
      data$Zhatup[i+1] <- data$s[i+1]*data$a[i+1]+(1+data$s[i+1]*(data$b[i+1]-1))*data$Zhat[i+1]
      
      data$c[i+1] <- max((sum(data$Aup[1:i])/data$id[i])-p, 0)
      data$riskup[i+1] <- (1/(1+exp(-data$Zhatup[i+1])))-data$c[i+1]
      data$Aup[i+1] <- ifelse(data$riskup[i+1]>=0, 1, 0)
      data$Zprobup[i+1] <- (1/(1+exp(-(0.5*data$Zhatup[i+1]+0.5))))-.2*data$Aup[i+1]
      data$Zrealup[i+1] <- rbinom(n=1, size = 1, prob = data$Zprobup[i+1])
    }
    
    datarecal[[k]] <- data
    
  }
  
  
  ithpatient <- function(data, j){
    
    data$Zhatfinal <- data[j,"s"]*data[j,"a"]+(1+data[j,"s"]*(data[j,"b"]-1))*data$Zhat
    data$riskfinal <- (1/(1+exp(-data$Zhatfinal)))-data[j,"c"]
    data$Afinal <- ifelse(data$riskfinal>=0, 1, 0)
    data$Zprobfinal <- (1/(1+exp(-(0.5*data$Zhatfinal+0.5))))-.2*data$Afinal
    
    for(i in 1:(nrow(data))) {
      data$Zrealfinal[i] <- rbinom(n=1, size = 1, prob = data$Zprobfinal[i])
    }
    
    data <- data[1:j,]
    data$riskfinalopt <- 0
    
    return(data)
    
  }
  
  
  p1500 <- future_lapply(datarecal, ithpatient, j=1500, future.seed = TRUE)
  p2500 <- future_lapply(datarecal, ithpatient, j=2500, future.seed = TRUE)
  p3500 <- future_lapply(datarecal, ithpatient, j=3500, future.seed = TRUE)
  
  rm(datarecal)
  
  
  final <- function(data, j=500, z=0.5) {
    
    j=j
    z=z
    
    for(i in 1:(j)) {
      ofopt <- function(par, x=data){
        
        #Extract guesses for standardized variables (slightly varied) par is just an example of a feasible solution.
        age.s <- par[1]
        sex.s <- par[2]
        BMI.s <- par[3]
        HDL.s <- par[4]
        trig.s <- par[5]
        gluc.s <- par[6]
        bp1.s <- par[7]
        bp2.s <- par[8]
        bp3.s <- par[9]
        hdiab.s <- par[10]
        
        
        #define raw variables based on optimized values (convert back standardized values to raw to be used inside log reg formula)
        
#age
        age1.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) < 50, 1, 0)
        age2.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) >= 50 & age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) < 65, 1, 0)
        age3.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) >= 65, 1, 0)
        #sex
        #sex.opt <- ifelse(sex.s*sd(x$RIAGENDR)+mean(x$RIAGENDR) >= 0.5, 1, 0)
        sex.opt <- min(max(sex.s*sd(x$RIAGENDR)+mean(x$RIAGENDR),0),1)
        #BMI
        BMI1.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) < 25, 1, 0)
        BMI2.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) >= 25 & BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) < 30, 1, 0)
        BMI3.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) >= 30, 1, 0)
        #HDL
        #HDL.opt <- ifelse((sex.opt == 1 & HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD)< 40) | (sex.opt == 0 & HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD) < 50), 1, 0)
        HDL.opt <- ifelse(HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD)< 40, 1, ifelse(HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD) >= 50, 0, (1-sex.opt)))
        #triglyceride
        trig.opt <- ifelse(trig.s*sd(x$LBXTR)+mean(x$LBXTR) >= 150, 1, 0)
        #fasting glucose
        gluc.opt <- ifelse(gluc.s*sd(x$LBXGLU)+mean(x$LBXGLU)>= 100, 1, 0)
        #blood pressure
        #bp3.opt <- ifelse(bp3.s*sd(x$BPQ050A)+mean(x$BPQ050A) >= 0.5, 1, 0) #bp treatment
        bp3.opt <-  min(max(bp3.s*sd(x$BPQ050A)+mean(x$BPQ050A),0),1)  #bp treatment
        #bp.opt <- ifelse(bp1.s*sd(x$BPXSY1)+mean(x$BPXSY1) >= 130 | bp2.s*sd(x$BPXDI1)+mean(x$BPXDI1) >=85 | bp3.opt == 1, 1, 0)
        bp.opt <- ifelse(bp1.s*sd(x$BPXSY1)+mean(x$BPXSY1) >= 130 | bp2.s*sd(x$BPXDI1)+mean(x$BPXDI1) >=85, 1, bp3.opt)
        #histofdiab
        hdiab.opt <- ifelse(hdiab.s*sd(x$DIQ175A)+mean(x$DIQ175A) >= 0.5, 1, 0)
        #hdiab.opt <- min(max(hdiab.s*sd(x$DIQ175A)+mean(x$DIQ175A),0),1)
        
        #Calculate new risk with slight variations
        
        Zhat.opt <- -5.517-0.018*age2.opt-0.081*age3.opt-0.010*sex.opt+0.565*hdiab.opt+0.301*BMI2.opt+0.92*BMI3.opt+0.498*bp.opt+0.944*HDL.opt+0.575*trig.opt+1.980*gluc.opt
        
        Zhatfinal.opt <- x[j,"s"]*x[j,"a"]+(1+x[j,"s"]*(x[j,"b"]-1))*Zhat.opt
        
        risk.opt <- 1/(1+exp(-Zhatfinal.opt))
        
        riskc.opt <- risk.opt-x[j,"c"]
        
        #constraints (subject to:)
        
        if(age.s <= x$age.s[i] + z &&
           age.s >= x$age.s[i] - z &&
           sex.s <= x$sex.s[i] + z &&
           sex.s >= x$sex.s[i] - z &&
           BMI.s <= x$BMI.s[i] + z &&
           BMI.s >= x$BMI.s[i] - z &&
           HDL.s <= x$HDL.s[i] + z &&
           HDL.s >= x$HDL.s[i] - z &&
           trig.s <= x$trig.s[i] + z &&
           trig.s >= x$trig.s[i] - z &&
           gluc.s <= x$glu.s[i] + z &&
           gluc.s >= x$glu.s[i] - z &&
           bp1.s <= x$bp1.s[i] + z &&
           bp1.s >= x$bp1.s[i] - z &&
           bp2.s <= x$bp2.s[i] + z &&
           bp2.s >= x$bp2.s[i] - z &&
           bp3.s <= x$bp3.s[i] + z &&
           bp3.s >= x$bp3.s[i] - z &&
           hdiab.s <= x$hdiab.s[i] + z &&
           hdiab.s >= x$hdiab.s[i] - z &&
           (sqrt((x$age.s[i]-age.s)^2+(x$sex.s[i]-sex.s)^2+(x$BMI.s[i]-BMI.s)^2+(x$HDL.s[i]-HDL.s)^2+(x$trig.s[i]-trig.s)^2+(x$glu.s[i]-gluc.s)^2+(x$bp1.s[i]-bp1.s)^2+(x$bp2.s[i]-bp2.s)^2+(x$bp3.s[i]-bp3.s)^2+(x$hdiab.s[i]-hdiab.s)^2)) <= z
        ) {riskc.opt}
       
      }
      
      #if final risk of patient is negative (positive) then maximize (minimize) optimization and save optimized value of risk after slight variations
      
      data$riskfinalopt[i] <- ifelse(data$riskfinal[i]>0, {optimx(par=c(
        age.s = data$age.s[i],
        sex.s = data$sex.s[i],
        BMI.s = data$BMI.s[i],
        HDL.s = data$HDL.s[i],
        trig.s = data$trig.s[i],
        gluc.s = data$glu.s[i],
        bp1.s = data$bp1.s[i],
        bp2.s = data$bp2.s[i],
        bp3.s = data$bp3.s[i],
        hdiab.s = data$hdiab.s[i]), ofopt, method = c("Nelder-Mead"), control=list(badval=NA))$value}, {optimx(par=c(age.s = data$age.s[i],
                                                                                                                     sex.s = data$sex.s[i],
                                                                                                                     BMI.s = data$BMI.s[i],
                                                                                                                     HDL.s = data$HDL.s[i],
                                                                                                                     trig.s = data$trig.s[i],
                                                                                                                     gluc.s = data$glu.s[i],
                                                                                                                     bp1.s = data$bp1.s[i],
                                                                                                                     bp2.s = data$bp2.s[i],
                                                                                                                     bp3.s = data$bp3.s[i],
                                                                                                                     hdiab.s = data$hdiab.s[i]), ofopt, method = c("Nelder-Mead"), control=list(maximize=TRUE, badval=NA))$value})
      
    }
    
    data$rand <- sign(data$riskfinal) != sign(data$riskfinalopt) #true means that patient changed signs
    #table(sign(data$riskfinal) != sign(data$riskfinalopt))
    #which(sign(data$riskfinal) != sign(data$riskfinalopt))
    
    return(data)
  }
  
  
  final2 <- function(data, j, z) {
    
      data$rand[is.na(data$rand)] <- 0
    
    for(i in 1:(j)) {
      ofopt <- function(par, x=data){
        
        #Extract guesses for standardized variables (slightly varied) par is just an example of a feasible solution.
        age.s <- par[1]
        sex.s <- par[2]
        BMI.s <- par[3]
        HDL.s <- par[4]
        trig.s <- par[5]
        gluc.s <- par[6]
        bp1.s <- par[7]
        bp2.s <- par[8]
        bp3.s <- par[9]
        hdiab.s <- par[10]
        
        
        #define raw variables based on optimized values (convert back standardized values to raw to be used inside log reg formula)
        
#age
        age1.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) < 50, 1, 0)
        age2.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) >= 50 & age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) < 65, 1, 0)
        age3.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) >= 65, 1, 0)
        #sex
        #sex.opt <- ifelse(sex.s*sd(x$RIAGENDR)+mean(x$RIAGENDR) >= 0.5, 1, 0)
        sex.opt <- min(max(sex.s*sd(x$RIAGENDR)+mean(x$RIAGENDR),0),1)
        #BMI
        BMI1.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) < 25, 1, 0)
        BMI2.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) >= 25 & BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) < 30, 1, 0)
        BMI3.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) >= 30, 1, 0)
        #HDL
        #HDL.opt <- ifelse((sex.opt == 1 & HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD)< 40) | (sex.opt == 0 & HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD) < 50), 1, 0)
        HDL.opt <- ifelse(HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD)< 40, 1, ifelse(HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD) >= 50, 0, (1-sex.opt)))
        #triglyceride
        trig.opt <- ifelse(trig.s*sd(x$LBXTR)+mean(x$LBXTR) >= 150, 1, 0)
        #fasting glucose
        gluc.opt <- ifelse(gluc.s*sd(x$LBXGLU)+mean(x$LBXGLU)>= 100, 1, 0)
        #blood pressure
        #bp3.opt <- ifelse(bp3.s*sd(x$BPQ050A)+mean(x$BPQ050A) >= 0.5, 1, 0) #bp treatment
        bp3.opt <-  min(max(bp3.s*sd(x$BPQ050A)+mean(x$BPQ050A),0),1)  #bp treatment
        #bp.opt <- ifelse(bp1.s*sd(x$BPXSY1)+mean(x$BPXSY1) >= 130 | bp2.s*sd(x$BPXDI1)+mean(x$BPXDI1) >=85 | bp3.opt == 1, 1, 0)
        bp.opt <- ifelse(bp1.s*sd(x$BPXSY1)+mean(x$BPXSY1) >= 130 | bp2.s*sd(x$BPXDI1)+mean(x$BPXDI1) >=85, 1, bp3.opt)
        #histofdiab
        hdiab.opt <- ifelse(hdiab.s*sd(x$DIQ175A)+mean(x$DIQ175A) >= 0.5, 1, 0)
        #hdiab.opt <- min(max(hdiab.s*sd(x$DIQ175A)+mean(x$DIQ175A),0),1)
        
        #Calculate new risk with slight variations
        
        Zhat.opt <- -5.517-0.018*age2.opt-0.081*age3.opt-0.010*sex.opt+0.565*hdiab.opt+0.301*BMI2.opt+0.92*BMI3.opt+0.498*bp.opt+0.944*HDL.opt+0.575*trig.opt+1.980*gluc.opt
        
        Zhatfinal.opt <- x[j,"s"]*x[j,"a"]+(1+x[j,"s"]*(x[j,"b"]-1))*Zhat.opt
        
        risk.opt <- 1/(1+exp(-Zhatfinal.opt))
        
        riskc.opt <- risk.opt-x[j,"c"]
        
        #constraints (subject to:)
        
        if(age.s <= x$age.s[i] + z &&
           age.s >= x$age.s[i] - z &&
           sex.s <= x$sex.s[i] + z &&
           sex.s >= x$sex.s[i] - z &&
           BMI.s <= x$BMI.s[i] + z &&
           BMI.s >= x$BMI.s[i] - z &&
           HDL.s <= x$HDL.s[i] + z &&
           HDL.s >= x$HDL.s[i] - z &&
           trig.s <= x$trig.s[i] + z &&
           trig.s >= x$trig.s[i] - z &&
           gluc.s <= x$glu.s[i] + z &&
           gluc.s >= x$glu.s[i] - z &&
           bp1.s <= x$bp1.s[i] + z &&
           bp1.s >= x$bp1.s[i] - z &&
           bp2.s <= x$bp2.s[i] + z &&
           bp2.s >= x$bp2.s[i] - z &&
           bp3.s <= x$bp3.s[i] + z &&
           bp3.s >= x$bp3.s[i] - z &&
           hdiab.s <= x$hdiab.s[i] + z &&
           hdiab.s >= x$hdiab.s[i] - z &&
           (sqrt((x$age.s[i]-age.s)^2+(x$sex.s[i]-sex.s)^2+(x$BMI.s[i]-BMI.s)^2+(x$HDL.s[i]-HDL.s)^2+(x$trig.s[i]-trig.s)^2+(x$glu.s[i]-gluc.s)^2+(x$bp1.s[i]-bp1.s)^2+(x$bp2.s[i]-bp2.s)^2+(x$bp3.s[i]-bp3.s)^2+(x$hdiab.s[i]-hdiab.s)^2)) <= z
        ){riskc.opt}
        
      }
      
      #if final risk of patient is negative (positive) then maximize (minimize) optimization and save optimized value of risk after slight variations
    
  
      data$riskfinalopt2[i]<- ifelse(data$rand[i] == "TRUE", {data$riskfinalopt[i]}, {ifelse(data$riskfinal[i]>0, {optimx(par=c(
        age.s = data$age.s[i],
        sex.s = data$sex.s[i],
        BMI.s = data$BMI.s[i],
        HDL.s = data$HDL.s[i],
        trig.s = data$trig.s[i],
        gluc.s = data$glu.s[i],
        bp1.s = data$bp1.s[i],
        bp2.s = data$bp2.s[i],
        bp3.s = data$bp3.s[i],
        hdiab.s = data$hdiab.s[i]), ofopt, method = c("Nelder-Mead"), control=list(badval=NA))$value}, {optimx(par=c(age.s = data$age.s[i],
        sex.s = data$sex.s[i],
        BMI.s = data$BMI.s[i],
        HDL.s = data$HDL.s[i],
        trig.s = data$trig.s[i],
        gluc.s = data$glu.s[i],
        bp1.s = data$bp1.s[i],
        bp2.s = data$bp2.s[i],
        bp3.s = data$bp3.s[i],
        hdiab.s = data$hdiab.s[i]), ofopt, method = c("Nelder-Mead"), control=list(maximize=TRUE, badval=NA))$value})})
  
    } 
      
    data$rand <- sign(data$riskfinal) != sign(data$riskfinalopt2) #true means that patient changed signs
    #table(sign(data$riskfinal) != sign(data$riskfinalopt))
    #which(sign(data$riskfinal) != sign(data$riskfinalopt))
    
    
    #data <- subset(data, rand == TRUE)
    return(data)
  }
  
  
result <- function(data
  ) {
    
    n <- tryCatch(table(data$rand)["TRUE"], error = function(e) return(NA))
    glm1 <- tryCatch(lm(Zrealfinal ~ Afinal + riskfinal + riskfinal:Afinal, data = data, subset = rand==TRUE), error = function(e) return(NA))
   EST <- tryCatch(coef(glm1)["Afinal"], error = function(e) return(NA))
    LB <- tryCatch(summary(glm1)$coefficients["Afinal",1]+qnorm(0.025)*summary(glm1)$coefficients["Afinal",2], error = function(e) return(NA))
    UB <- tryCatch(summary(glm1)$coefficients["Afinal",1]+qnorm(0.975)*summary(glm1)$coefficients["Afinal",2], error = function(e) return(NA))
    Error <- tryCatch(EST-(-0.2), error = function(e) return(NA))
    #Errorlog <- tryCatch(coef(glm1)["Afinal"]-log(0.5), error = function(e) return(NA))
    Coverage <- tryCatch(between(-0.2, LB, UB), error = function(e) return(NA))
    
    c(n, EST, LB, UB, Error, Coverage)
    
  }
  
  p1500z0.5 <- future_lapply(p1500, final, j=1500, z=0.5)
  rm(p1500)
  p1500z0.5.r <- data.frame(t(sapply(p1500z0.5, result)))
  colnames(p1500z0.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  
  
  p1500z1 <- future_lapply(p1500z0.5, final2, j=1500, z=1)
  rm(p1500z0.5)
  p1500z1.r <- data.frame(t(sapply(p1500z1, result)))
  colnames(p1500z1.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  

  p1500z1.5 <- future_lapply(p1500z1, final2, j=1500, z=1.5)
  rm(p1500z1)
  p1500z1.5.r <- data.frame(t(sapply(p1500z1.5, result)))
  colnames(p1500z1.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  rm(p1500z1.5)
  
  
  
   p2500z0.5 <- future_lapply(p2500, final, j=2500, z=0.5)
  rm(p2500)
  p2500z0.5.r <- data.frame(t(sapply(p2500z0.5, result)))
  colnames(p2500z0.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  
  p2500z1 <- future_lapply(p2500z0.5, final2, j=2500, z=1)
  rm(p2500z0.5)
  p2500z1.r <- data.frame(t(sapply(p2500z1, result)))
  colnames(p2500z1.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  
  p2500z1.5 <- future_lapply(p2500z1, final2, j=2500, z=1.5)
  rm(p2500z1)
  p2500z1.5.r <- data.frame(t(sapply(p2500z1.5, result)))
  colnames(p2500z1.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  rm(p2500z1.5)
  

  
  p3500z0.5 <- future_lapply(p3500, final, j=3500, z=0.5)
  rm(p3500)
  p3500z0.5.r <- data.frame(t(sapply(p3500z0.5, result)))
  colnames(p3500z0.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  
  
  p3500z1 <- future_lapply(p3500z0.5, final2, j=3500, z=1)
  rm(p3500z0.5)
  p3500z1.r <- data.frame(t(sapply(p3500z1, result)))
  colnames(p3500z1.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  
  
  p3500z1.5 <- future_lapply(p3500z1, final2, j=3500, z=1.5)
  rm(p3500z1)
  p3500z1.5.r <- data.frame(t(sapply(p3500z1.5, result)))
  colnames(p3500z1.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  rm(p3500z1.5)
  
  
  #final output
  return(list(p1500z0.5.r, p2500z0.5.r, p3500z0.5.r, p1500z1.r, p2500z1.r, p3500z1.r, p1500z1.5.r, p2500z1.5.r, p3500z1.5.r))
  
}

```



#execute function:
```{r}
library(future.apply)
plan(multisession, workers = 20)

start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=0)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s.0_run1.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)


start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=0)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s.0_run2.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)


start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=0)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s.0_run3.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)

start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=0)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s.0_run4.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)

start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=0)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s.0_run5.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)
```



```{r}
library(future.apply)
plan(multisession, workers = 20)

start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=0)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s.0_run6.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)


start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=0)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s.0_run7.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)


start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=0)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s.0_run8.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)

start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=0)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s.0_run9.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)

start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=0)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s.0_run10.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)
```

#s=1 2000 reps

```{r}
library(future.apply)
plan(multisession, workers = 20)

start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=1)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s1_run1.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)


start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=1)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s1_run2.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)


start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=1)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s1_run3.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)

start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=1)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s1_run4.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)

start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=1)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s1_run5.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)


start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=1)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s1_run6.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)


start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=1)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s1_run7.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)


start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=1)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s1_run8.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)

start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=1)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s1_run9.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)

start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=1)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s1_run10.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)
```


#s=0.5


```{r}
library(future.apply)
plan(multisession, workers = 20)

start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=0.5)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s.0.5_run6.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)


start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=0.5)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s.0.5_run7.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)


start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=0.5)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s.0.5_run8.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)

start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=0.5)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s.0.5_run9.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)

start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=200, p=.5, s=0.5)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s.0.5_run10.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)
```


```{r, include=FALSE}
start <- Sys.time()
rec.p.5s.5 <- recalcutp(reps=100, p=.5, s=.5)
print(Sys.time()-start)

names(rec.p.5s.5) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.5, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s.5.xlsx", sheetName = names(rec.p.5s.5), rowNames = FALSE)
rm(rec.p.5s.5)


start <- Sys.time()
rec.p.5s.1 <- recalcutp(reps=100, p=.5, s=1)
print(Sys.time()-start)

names(rec.p.5s.1) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.1, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s.1.xlsx", sheetName = names(rec.p.5s.1), rowNames = FALSE)
rm(rec.p.5s.1)

start <- Sys.time()
rec.p.5s.0 <- recalcutp(reps=100, p=.5, s=0)
print(Sys.time()-start)

names(rec.p.5s.0) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rec.p.5s.0, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rec.p.5s.0.xlsx", sheetName = names(rec.p.5s.0), rowNames = FALSE)
rm(rec.p.5s.0)
```




#Recal with cutoff fixed function:
```{r}
library(future.apply)
plan(multisession, workers = 20)

recalcut <- function(reps=10, s= 0, c=.1) {
  
  datarecal <- list()
  for(k in 1:reps) {
    
    data <- dataraw[sample(c(1:nrow(dataraw)), size=3500, replace=TRUE),]
    
    
    data$id <- seq(1, nrow(data))
    
    
    
    data$a <- 0
    data$b <- 0
    
    
    data$s <- s #static risk pred model
    
    
    data$Zhatup <- data$Zhat
    data$riskup <- data$risk
    data$Aup <- data$A
    data$Zprobup <- data$Zprob
    data$Zrealup <- data$Zreal
    
    
    #fit a log reg and update linear predictor
    for(i in 200:(nrow(data)-1)) {
      calibrate <- glm(Zrealup~Zhatup, family = "binomial", data = data[1:i,], subset = Aup==0)
      data$a[i+1] <- calibrate$coefficients[[1]]
      data$b[i+1] <- calibrate$coefficients[[2]]
      data$Zhatup[i+1] <- data$s[i+1]*data$a[i+1]+(1+data$s[i+1]*(data$b[i+1]-1))*data$Zhat[i+1]
      data$riskup[i+1] <- (1/(1+exp(-data$Zhatup[i+1])))-c
      data$Aup[i+1] <- ifelse(data$riskup[i+1]>=0, 1, 0)
      data$Zprobup[i+1] <- (1/(1+exp(-(0.5*data$Zhatup[i+1]+0.5))))-.2*data$Aup[i+1]
      data$Zrealup[i+1] <- rbinom(n=1, size = 1, prob = data$Zprobup[i+1])
    }
    
    datarecal[[k]] <- data
    
  }
  
  
  ithpatient <- function(data, j){
    
    data$Zhatfinal <- data[j,"s"]*data[j,"a"]+(1+data[j,"s"]*(data[j,"b"]-1))*data$Zhat
    data$riskfinal <- (1/(1+exp(-data$Zhatfinal)))-c
    data$Afinal <- ifelse(data$riskfinal>=0, 1, 0)
    data$Zprobfinal <- (1/(1+exp(-(0.5*data$Zhatfinal+0.5))))-.2*data$Afinal

    
    for(i in 1:(nrow(data))) {
      data$Zrealfinal[i] <- rbinom(n=1, size = 1, prob = data$Zprobfinal[i])
    }
    
    data <- data[1:j,]
    data$riskfinalopt <- 0
    
    return(data)
    
  }
  
  
  p1500 <- future_lapply(datarecal, ithpatient, j=1500, future.seed = TRUE)
  p2500 <- future_lapply(datarecal, ithpatient, j=2500, future.seed = TRUE)
  p3500 <- future_lapply(datarecal, ithpatient, j=3500, future.seed = TRUE)
  
  rm(datarecal)
  
  final <- function(data, j=500, z=0.5) {
    
    j=j
    z=z
    
    for(i in 1:(j)) {
      ofopt <- function(par, x=data){
        
        #Extract guesses for standardized variables (slightly varied) par is just an example of a feasible solution.
        age.s <- par[1]
        sex.s <- par[2]
        BMI.s <- par[3]
        HDL.s <- par[4]
        trig.s <- par[5]
        gluc.s <- par[6]
        bp1.s <- par[7]
        bp2.s <- par[8]
        bp3.s <- par[9]
        hdiab.s <- par[10]
        
        
        #define raw variables based on optimized values (convert back standardized values to raw to be used inside log reg formula)
        
        #age
        age1.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) < 50, 1, 0)
        age2.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) >= 50 & age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) < 65, 1, 0)
        age3.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) >= 65, 1, 0)
        #sex
        #sex.opt <- ifelse(sex.s*sd(x$RIAGENDR)+mean(x$RIAGENDR) >= 0.5, 1, 0)
        sex.opt <- min(max(sex.s*sd(x$RIAGENDR)+mean(x$RIAGENDR),0),1)
        #BMI
        BMI1.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) < 25, 1, 0)
        BMI2.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) >= 25 & BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) < 30, 1, 0)
        BMI3.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) >= 30, 1, 0)
        #HDL
        #HDL.opt <- ifelse((sex.opt == 1 & HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD)< 40) | (sex.opt == 0 & HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD) < 50), 1, 0)
        HDL.opt <- ifelse(HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD)< 40, 1, ifelse(HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD) >= 50, 0, (1-sex.opt)))
        #triglyceride
        trig.opt <- ifelse(trig.s*sd(x$LBXTR)+mean(x$LBXTR) >= 150, 1, 0)
        #fasting glucose
        gluc.opt <- ifelse(gluc.s*sd(x$LBXGLU)+mean(x$LBXGLU)>= 100, 1, 0)
        #blood pressure
        #bp3.opt <- ifelse(bp3.s*sd(x$BPQ050A)+mean(x$BPQ050A) >= 0.5, 1, 0) #bp treatment
        bp3.opt <-  min(max(bp3.s*sd(x$BPQ050A)+mean(x$BPQ050A),0),1)  #bp treatment
        #bp.opt <- ifelse(bp1.s*sd(x$BPXSY1)+mean(x$BPXSY1) >= 130 | bp2.s*sd(x$BPXDI1)+mean(x$BPXDI1) >=85 | bp3.opt == 1, 1, 0)
        bp.opt <- ifelse(bp1.s*sd(x$BPXSY1)+mean(x$BPXSY1) >= 130 | bp2.s*sd(x$BPXDI1)+mean(x$BPXDI1) >=85, 1, bp3.opt)
        #histofdiab
        hdiab.opt <- ifelse(hdiab.s*sd(x$DIQ175A)+mean(x$DIQ175A) >= 0.5, 1, 0)
        #hdiab.opt <- min(max(hdiab.s*sd(x$DIQ175A)+mean(x$DIQ175A),0),1)
        
        #Calculate new risk with slight variations
        
        Zhat.opt <- -5.517-0.018*age2.opt-0.081*age3.opt-0.010*sex.opt+0.565*hdiab.opt+0.301*BMI2.opt+0.92*BMI3.opt+0.498*bp.opt+0.944*HDL.opt+0.575*trig.opt+1.980*gluc.opt
        
        Zhatfinal.opt <- x[j,"s"]*x[j,"a"]+(1+x[j,"s"]*(x[j,"b"]-1))*Zhat.opt
        
        risk.opt <- 1/(1+exp(-Zhatfinal.opt))
        
        riskc.opt <- risk.opt-c
        
        #constraints (subject to:)
        
        if(age.s <= x$age.s[i] + z &&
           age.s >= x$age.s[i] - z &&
           sex.s <= x$sex.s[i] + z &&
           sex.s >= x$sex.s[i] - z &&
           BMI.s <= x$BMI.s[i] + z &&
           BMI.s >= x$BMI.s[i] - z &&
           HDL.s <= x$HDL.s[i] + z &&
           HDL.s >= x$HDL.s[i] - z &&
           trig.s <= x$trig.s[i] + z &&
           trig.s >= x$trig.s[i] - z &&
           gluc.s <= x$glu.s[i] + z &&
           gluc.s >= x$glu.s[i] - z &&
           bp1.s <= x$bp1.s[i] + z &&
           bp1.s >= x$bp1.s[i] - z &&
           bp2.s <= x$bp2.s[i] + z &&
           bp2.s >= x$bp2.s[i] - z &&
           bp3.s <= x$bp3.s[i] + z &&
           bp3.s >= x$bp3.s[i] - z &&
           hdiab.s <= x$hdiab.s[i] + z &&
           hdiab.s >= x$hdiab.s[i] - z &&
           (sqrt((x$age.s[i]-age.s)^2+(x$sex.s[i]-sex.s)^2+(x$BMI.s[i]-BMI.s)^2+(x$HDL.s[i]-HDL.s)^2+(x$trig.s[i]-trig.s)^2+(x$glu.s[i]-gluc.s)^2+(x$bp1.s[i]-bp1.s)^2+(x$bp2.s[i]-bp2.s)^2+(x$bp3.s[i]-bp3.s)^2+(x$hdiab.s[i]-hdiab.s)^2)) <= z
        ){riskc.opt}
      }
      
      #if final risk of patient is negative (positive) then maximize (minimize) optimization and save optimized value of risk after slight variations
      
      data$riskfinalopt[i] <- ifelse(data$riskfinal[i]>0, {optimx(par=c(
        age.s = data$age.s[i],
        sex.s = data$sex.s[i],
        BMI.s = data$BMI.s[i],
        HDL.s = data$HDL.s[i],
        trig.s = data$trig.s[i],
        gluc.s = data$glu.s[i],
        bp1.s = data$bp1.s[i],
        bp2.s = data$bp2.s[i],
        bp3.s = data$bp3.s[i],
        hdiab.s = data$hdiab.s[i]), ofopt, method = c("Nelder-Mead"), control=list(badval=NA))$value}, {optimx(par=c(age.s = data$age.s[i],
                                                                                                                     sex.s = data$sex.s[i],
                                                                                                                     BMI.s = data$BMI.s[i],
                                                                                                                     HDL.s = data$HDL.s[i],
                                                                                                                     trig.s = data$trig.s[i],
                                                                                                                     gluc.s = data$glu.s[i],
                                                                                                                     bp1.s = data$bp1.s[i],
                                                                                                                     bp2.s = data$bp2.s[i],
                                                                                                                     bp3.s = data$bp3.s[i],
                                                                                                                     hdiab.s = data$hdiab.s[i]), ofopt, method = c("Nelder-Mead"), control=list(maximize=TRUE, badval=NA))$value})
      
    }
    
    data$rand <- sign(data$riskfinal) != sign(data$riskfinalopt) #true means that patient changed signs
    #table(sign(data$riskfinal) != sign(data$riskfinalopt))
    #which(sign(data$riskfinal) != sign(data$riskfinalopt))
    
    
    return(data)
  }
  
  
  
  final2 <- function(data, j, z) {
    
      data$rand[is.na(data$rand)] <- 0
    
    for(i in 1:(j)) {
      ofopt <- function(par, x=data){
        
        #Extract guesses for standardized variables (slightly varied) par is just an example of a feasible solution.
        age.s <- par[1]
        sex.s <- par[2]
        BMI.s <- par[3]
        HDL.s <- par[4]
        trig.s <- par[5]
        gluc.s <- par[6]
        bp1.s <- par[7]
        bp2.s <- par[8]
        bp3.s <- par[9]
        hdiab.s <- par[10]
        
        
        #define raw variables based on optimized values (convert back standardized values to raw to be used inside log reg formula)
        
#age
        age1.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) < 50, 1, 0)
        age2.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) >= 50 & age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) < 65, 1, 0)
        age3.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) >= 65, 1, 0)
        #sex
        #sex.opt <- ifelse(sex.s*sd(x$RIAGENDR)+mean(x$RIAGENDR) >= 0.5, 1, 0)
        sex.opt <- min(max(sex.s*sd(x$RIAGENDR)+mean(x$RIAGENDR),0),1)
        #BMI
        BMI1.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) < 25, 1, 0)
        BMI2.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) >= 25 & BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) < 30, 1, 0)
        BMI3.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) >= 30, 1, 0)
        #HDL
        #HDL.opt <- ifelse((sex.opt == 1 & HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD)< 40) | (sex.opt == 0 & HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD) < 50), 1, 0)
        HDL.opt <- ifelse(HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD)< 40, 1, ifelse(HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD) >= 50, 0, (1-sex.opt)))
        #triglyceride
        trig.opt <- ifelse(trig.s*sd(x$LBXTR)+mean(x$LBXTR) >= 150, 1, 0)
        #fasting glucose
        gluc.opt <- ifelse(gluc.s*sd(x$LBXGLU)+mean(x$LBXGLU)>= 100, 1, 0)
        #blood pressure
        #bp3.opt <- ifelse(bp3.s*sd(x$BPQ050A)+mean(x$BPQ050A) >= 0.5, 1, 0) #bp treatment
        bp3.opt <-  min(max(bp3.s*sd(x$BPQ050A)+mean(x$BPQ050A),0),1)  #bp treatment
        #bp.opt <- ifelse(bp1.s*sd(x$BPXSY1)+mean(x$BPXSY1) >= 130 | bp2.s*sd(x$BPXDI1)+mean(x$BPXDI1) >=85 | bp3.opt == 1, 1, 0)
        bp.opt <- ifelse(bp1.s*sd(x$BPXSY1)+mean(x$BPXSY1) >= 130 | bp2.s*sd(x$BPXDI1)+mean(x$BPXDI1) >=85, 1, bp3.opt)
        #histofdiab
        hdiab.opt <- ifelse(hdiab.s*sd(x$DIQ175A)+mean(x$DIQ175A) >= 0.5, 1, 0)
        #hdiab.opt <- min(max(hdiab.s*sd(x$DIQ175A)+mean(x$DIQ175A),0),1)
        
        #Calculate new risk with slight variations
        
        Zhat.opt <- -5.517-0.018*age2.opt-0.081*age3.opt-0.010*sex.opt+0.565*hdiab.opt+0.301*BMI2.opt+0.92*BMI3.opt+0.498*bp.opt+0.944*HDL.opt+0.575*trig.opt+1.980*gluc.opt
        
        Zhatfinal.opt <- x[j,"s"]*x[j,"a"]+(1+x[j,"s"]*(x[j,"b"]-1))*Zhat.opt
        
        risk.opt <- 1/(1+exp(-Zhatfinal.opt))
        
        riskc.opt <- risk.opt-c
        
        #constraints (subject to:)
        
        if(age.s <= x$age.s[i] + z &&
           age.s >= x$age.s[i] - z &&
           sex.s <= x$sex.s[i] + z &&
           sex.s >= x$sex.s[i] - z &&
           BMI.s <= x$BMI.s[i] + z &&
           BMI.s >= x$BMI.s[i] - z &&
           HDL.s <= x$HDL.s[i] + z &&
           HDL.s >= x$HDL.s[i] - z &&
           trig.s <= x$trig.s[i] + z &&
           trig.s >= x$trig.s[i] - z &&
           gluc.s <= x$glu.s[i] + z &&
           gluc.s >= x$glu.s[i] - z &&
           bp1.s <= x$bp1.s[i] + z &&
           bp1.s >= x$bp1.s[i] - z &&
           bp2.s <= x$bp2.s[i] + z &&
           bp2.s >= x$bp2.s[i] - z &&
           bp3.s <= x$bp3.s[i] + z &&
           bp3.s >= x$bp3.s[i] - z &&
           hdiab.s <= x$hdiab.s[i] + z &&
           hdiab.s >= x$hdiab.s[i] - z &&
           (sqrt((x$age.s[i]-age.s)^2+(x$sex.s[i]-sex.s)^2+(x$BMI.s[i]-BMI.s)^2+(x$HDL.s[i]-HDL.s)^2+(x$trig.s[i]-trig.s)^2+(x$glu.s[i]-gluc.s)^2+(x$bp1.s[i]-bp1.s)^2+(x$bp2.s[i]-bp2.s)^2+(x$bp3.s[i]-bp3.s)^2+(x$hdiab.s[i]-hdiab.s)^2)) <= z
        ){riskc.opt}
        
      }
      
      #if final risk of patient is negative (positive) then maximize (minimize) optimization and save optimized value of risk after slight variations
    
  
      data$riskfinalopt2[i]<- ifelse(data$rand[i] == "TRUE", {data$riskfinalopt[i]}, {ifelse(data$riskfinal[i]>0, {optimx(par=c(
        age.s = data$age.s[i],
        sex.s = data$sex.s[i],
        BMI.s = data$BMI.s[i],
        HDL.s = data$HDL.s[i],
        trig.s = data$trig.s[i],
        gluc.s = data$glu.s[i],
        bp1.s = data$bp1.s[i],
        bp2.s = data$bp2.s[i],
        bp3.s = data$bp3.s[i],
        hdiab.s = data$hdiab.s[i]), ofopt, method = c("Nelder-Mead"), control=list(badval=NA))$value}, {optimx(par=c(age.s = data$age.s[i],
        sex.s = data$sex.s[i],
        BMI.s = data$BMI.s[i],
        HDL.s = data$HDL.s[i],
        trig.s = data$trig.s[i],
        gluc.s = data$glu.s[i],
        bp1.s = data$bp1.s[i],
        bp2.s = data$bp2.s[i],
        bp3.s = data$bp3.s[i],
        hdiab.s = data$hdiab.s[i]), ofopt, method = c("Nelder-Mead"), control=list(maximize=TRUE, badval=NA))$value})})
  
    } 

    data$rand <- sign(data$riskfinal) != sign(data$riskfinalopt2) #true means that patient changed signs
    #table(sign(data$riskfinal) != sign(data$riskfinalopt))
    #which(sign(data$riskfinal) != sign(data$riskfinalopt))
    
    return(data)
  }
  
result <- function(data
  ) {
    
    n <- tryCatch(table(data$rand)["TRUE"], error = function(e) return(NA))
    glm1 <- tryCatch(lm(Zrealfinal ~ Afinal + riskfinal + riskfinal:Afinal, data = data, subset = rand==TRUE), error = function(e) return(NA))
   EST <- tryCatch(coef(glm1)["Afinal"], error = function(e) return(NA))
    LB <- tryCatch(summary(glm1)$coefficients["Afinal",1]+qnorm(0.025)*summary(glm1)$coefficients["Afinal",2], error = function(e) return(NA))
    UB <- tryCatch(summary(glm1)$coefficients["Afinal",1]+qnorm(0.975)*summary(glm1)$coefficients["Afinal",2], error = function(e) return(NA))
    Error <- tryCatch(EST-(-0.2), error = function(e) return(NA))
    #Errorlog <- tryCatch(coef(glm1)["Afinal"]-log(0.5), error = function(e) return(NA))
    Coverage <- tryCatch(between(-0.2, LB, UB), error = function(e) return(NA))
    
    c(n, EST, LB, UB, Error, Coverage)
    
  }
  
  p1500z0.5 <- future_lapply(p1500, final, j=1500, z=0.5)
  rm(p1500)
  p1500z0.5.r <- data.frame(t(sapply(p1500z0.5, result)))
  colnames(p1500z0.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  
  
  p1500z1 <- future_lapply(p1500z0.5, final2, j=1500, z=1)
  rm(p1500z0.5)
  p1500z1.r <- data.frame(t(sapply(p1500z1, result)))
  colnames(p1500z1.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  

  p1500z1.5 <- future_lapply(p1500z1, final2, j=1500, z=1.5)
  rm(p1500z1)
  p1500z1.5.r <- data.frame(t(sapply(p1500z1.5, result)))
  colnames(p1500z1.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  rm(p1500z1.5)
  

  
  
   p2500z0.5 <- future_lapply(p2500, final, j=2500, z=0.5)
  rm(p2500)
  p2500z0.5.r <- data.frame(t(sapply(p2500z0.5, result)))
  colnames(p2500z0.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  
  p2500z1 <- future_lapply(p2500z0.5, final2, j=2500, z=1)
  rm(p2500z0.5)
  p2500z1.r <- data.frame(t(sapply(p2500z1, result)))
  colnames(p2500z1.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  
  p2500z1.5 <- future_lapply(p2500z1, final2, j=2500, z=1.5)
  rm(p2500z1)
  p2500z1.5.r <- data.frame(t(sapply(p2500z1.5, result)))
  colnames(p2500z1.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  rm(p2500z1.5)
  
  
  p3500z0.5 <- future_lapply(p3500, final, j=3500, z=0.5)
  rm(p3500)
  p3500z0.5.r <- data.frame(t(sapply(p3500z0.5, result)))
  colnames(p3500z0.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  
  
  p3500z1 <- future_lapply(p3500z0.5, final2, j=3500, z=1)
  rm(p3500z0.5)
  p3500z1.r <- data.frame(t(sapply(p3500z1, result)))
  colnames(p3500z1.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  
  
  p3500z1.5 <- future_lapply(p3500z1, final2, j=3500, z=1.5)
  rm(p3500z1)
  p3500z1.5.r <- data.frame(t(sapply(p3500z1.5, result)))
  colnames(p3500z1.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  rm(p3500z1.5)
  
  
  
  
  #final output
  return(list(p1500z0.5.r, p2500z0.5.r, p3500z0.5.r, p1500z1.r, p2500z1.r, p3500z1.r, p1500z1.5.r, p2500z1.5.r, p3500z1.5.r))
  
}



```






#Rev with cutoff p function:
```{r}
library(future.apply)
plan(multisession, workers = 20)

revcutp <- function(reps=20, p =.5, s= 0) {
  
  datarecal <- list()
  for(k in 1:reps) {
    
    data <- dataraw[sample(c(1:nrow(dataraw)), size=3500, replace=TRUE),]
    
    
    data$id <- seq(1, nrow(data))
    
    
    for(i in 2:200) {
      
      data$c[i] <- max((sum(data$A[1:i-1])/data$id[i-1])-p, 0)
      data$risk[i] <- (1/(1+exp(-data$Zhat[i])))-data$c[i]
      data$A[i] <- ifelse(data$risk[i]>=0, 1, 0)
      data$Zprob[i] <- (1/(1+exp(-(0.5*data$Zhat[i]+0.5))))-.2*data$A[i]
        
      data$Zreal[i] <- rbinom(n=1, size = 1, prob = data$Zprob[i])
    }
    
    
    data$s <- s #static risk pred model
    
    data$int_betarev <- 0
    data$age2_betarev <- 0
    data$age3_betarev <- 0
    data$RIAGENDR_betarev <- 0
    data$DIQ175A_betarev <- 0
    data$BMI2_betarev <- 0
    data$BMI3_betarev <- 0
    data$bp_betarev <- 0
    data$HDL_betarev <- 0
    data$trig_betarev <- 0
    data$glucose_betarev <- 0
    data$Zhatup <- data$Zhat
    data$riskup <- data$risk
    data$Aup <- data$A
    data$Zprobup <- data$Zprob
    data$Zrealup <- data$Zreal
    
    #fit a log reg and update linear predictor
    for(i in 200:(nrow(data)-1)) {
  
      #revise (fit a new regression model)
revise <- glm(Zrealup~age+RIAGENDR+DIQ175A+BMI+bp+HDL+trig+glucose, family = "binomial", data=data[1:i,], subset = Aup==0)

  #new models betas after shrinkage
#data$Zhatrev[i+1] <- predict(revise, newdata=data[i+1,])
data$int_betarev[i+1] <- tryCatch((-5.517)+data$s[i+1]*(revise$coefficients[[1]]-(-5.517)), error = function(e) return(-5.517))
data$age2_betarev[i+1] <- tryCatch((-0.018)+data$s[i+1]*(revise$coefficients[[2]]-(-0.018)), error = function(e) return(-0.018))
data$age3_betarev[i+1] <- tryCatch((-0.081)+data$s[i+1]*(revise$coefficients[[3]]-(-0.081)), error = function(e) return(-0.081))
data$RIAGENDR_betarev[i+1] <- tryCatch((-0.010)+data$s[i+1]*(revise$coefficients[[4]]-(-0.010)), error = function(e) return(-0.010))
data$DIQ175A_betarev[i+1] <- tryCatch((0.565)+data$s[i+1]*(revise$coefficients[[5]]-(0.565)), error = function(e) return(0.565))
data$BMI2_betarev[i+1] <- tryCatch((0.301)+data$s[i+1]*(revise$coefficients[[6]]-(0.301)), error = function(e) return(0.301))
data$BMI3_betarev[i+1] <- tryCatch((0.92)+data$s[i+1]*(revise$coefficients[[7]]-(0.92)), error = function(e) return(0.92))
data$bp_betarev[i+1] <- tryCatch((0.498)+data$s[i+1]*(revise$coefficients[[8]]-(0.498)), error = function(e) return(0.498))
data$HDL_betarev[i+1] <- tryCatch((0.944)+data$s[i+1]*(revise$coefficients[[9]]-(0.944)), error = function(e) return(0.944))
data$trig_betarev[i+1] <- tryCatch((0.575)+data$s[i+1]*(revise$coefficients[[10]]-(0.575)), error = function(e) return(0.575))
data$glucose_betarev[i+1] <- tryCatch((1.980)+data$s[i+1]*(revise$coefficients[[11]]-(1.980)), error = function(e) return(1.980))

data$Zhatup[i+1] <- data$int_betarev[i+1]+data$age2_betarev[i+1]*data$age2[i+1]+data$age3_betarev[i+1]*data$age3[i+1]+data$RIAGENDR_betarev[i+1]*data$RIAGENDR[i+1]+data$DIQ175A_betarev[i+1]*data$DIQ175A[i+1]+data$BMI2_betarev[i+1]*data$BMI2[i+1]+data$BMI3_betarev[i+1]*data$BMI3[i+1]+data$bp_betarev[i+1]*data$bp[i+1]+data$HDL_betarev[i+1]*data$HDL[i+1]+data$trig_betarev[i+1]*data$trig[i+1]+data$glucose_betarev[i+1]*data$glucose[i+1]
      
      data$c[i+1] <- max((sum(data$Aup[1:i])/data$id[i])-p, 0)
      data$riskup[i+1] <- (1/(1+exp(-data$Zhatup[i+1])))-data$c[i+1]
      data$Aup[i+1] <- ifelse(data$riskup[i+1]>=0, 1, 0)
      data$Zprobup[i+1] <- (1/(1+exp(-(0.5*data$Zhatup[i+1]+0.5))))-.2*data$Aup[i+1]

      data$Zrealup[i+1] <- rbinom(n=1, size = 1, prob = data$Zprobup[i+1])
    }
    
    datarecal[[k]] <- data
    
  }
  
  
  ithpatient <- function(data, j){
    
    data$Zhatfinal <- data$int_betarev[j]+data$age2_betarev[j]*data$age2+data$age3_betarev[j]*data$age3+data$RIAGENDR_betarev[j]*data$RIAGENDR+data$DIQ175A_betarev[j] *data$DIQ175A+data$BMI2_betarev[j]*data$BMI2+data$BMI3_betarev[j] *data$BMI3+data$bp_betarev[j]*data$bp+data$HDL_betarev[j]*data$HDL+data$trig_betarev[j]*data$trig+data$glucose_betarev[j]*data$glucose
    data$riskfinal <- (1/(1+exp(-data$Zhatfinal)))-data[j,"c"]
    data$Afinal <- ifelse(data$riskfinal>=0, 1, 0)
    data$Zprobfinal <- (1/(1+exp(-(0.5*data$Zhatfinal+0.5))))-.2*data$Afinal
    
    for(i in 1:(nrow(data))) {
      data$Zrealfinal[i] <- rbinom(n=1, size = 1, prob = data$Zprobfinal[i])
    }
    
    data <- data[1:j,]
    data$riskfinalopt <- 0
    
    return(data)
    
  }
  
  
  p1500 <- future_lapply(datarecal, ithpatient, j=1500, future.seed = TRUE)
  p2500 <- future_lapply(datarecal, ithpatient, j=2500, future.seed = TRUE)
  p3500 <- future_lapply(datarecal, ithpatient, j=3500, future.seed = TRUE)
  
  rm(datarecal)
  
  
  final <- function(data, j=500, z=0.5) {
    
    j=j
    z=z
    
    for(i in 1:(j)) {
      ofopt <- function(par, x=data){
        
        #Extract guesses for standardized variables (slightly varied) par is just an example of a feasible solution.
        age.s <- par[1]
        sex.s <- par[2]
        BMI.s <- par[3]
        HDL.s <- par[4]
        trig.s <- par[5]
        gluc.s <- par[6]
        bp1.s <- par[7]
        bp2.s <- par[8]
        bp3.s <- par[9]
        hdiab.s <- par[10]
        
        
        #define raw variables based on optimized values (convert back standardized values to raw to be used inside log reg formula)
        
        #age
        age1.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) < 50, 1, 0)
        age2.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) >= 50 & age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) < 65, 1, 0)
        age3.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) >= 65, 1, 0)
        #sex
        #sex.opt <- ifelse(sex.s*sd(x$RIAGENDR)+mean(x$RIAGENDR) >= 0.5, 1, 0)
        sex.opt <- min(max(sex.s*sd(x$RIAGENDR)+mean(x$RIAGENDR),0),1)
        #BMI
        BMI1.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) < 25, 1, 0)
        BMI2.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) >= 25 & BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) < 30, 1, 0)
        BMI3.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) >= 30, 1, 0)
        #HDL
        #HDL.opt <- ifelse((sex.opt == 1 & HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD)< 40) | (sex.opt == 0 & HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD) < 50), 1, 0)
        HDL.opt <- ifelse(HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD)< 40, 1, ifelse(HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD) >= 50, 0, (1-sex.opt)))
        #triglyceride
        trig.opt <- ifelse(trig.s*sd(x$LBXTR)+mean(x$LBXTR) >= 150, 1, 0)
        #fasting glucose
        gluc.opt <- ifelse(gluc.s*sd(x$LBXGLU)+mean(x$LBXGLU)>= 100, 1, 0)
        #blood pressure
        #bp3.opt <- ifelse(bp3.s*sd(x$BPQ050A)+mean(x$BPQ050A) >= 0.5, 1, 0) #bp treatment
        bp3.opt <-  min(max(bp3.s*sd(x$BPQ050A)+mean(x$BPQ050A),0),1)  #bp treatment
        #bp.opt <- ifelse(bp1.s*sd(x$BPXSY1)+mean(x$BPXSY1) >= 130 | bp2.s*sd(x$BPXDI1)+mean(x$BPXDI1) >=85 | bp3.opt == 1, 1, 0)
        bp.opt <- ifelse(bp1.s*sd(x$BPXSY1)+mean(x$BPXSY1) >= 130 | bp2.s*sd(x$BPXDI1)+mean(x$BPXDI1) >=85, 1, bp3.opt)
        #histofdiab
        hdiab.opt <- ifelse(hdiab.s*sd(x$DIQ175A)+mean(x$DIQ175A) >= 0.5, 1, 0)
        #hdiab.opt <- min(max(hdiab.s*sd(x$DIQ175A)+mean(x$DIQ175A),0),1)
        
        #Calculate new risk with slight variations

        
Zhatfinal.opt <- x$int_betarev[j]+x$age2_betarev[j]*age2.opt+x$age3_betarev[j]*age3.opt+x$RIAGENDR_betarev[j]*sex.opt+x$DIQ175A_betarev[j]*hdiab.opt+x$BMI2_betarev[j]*BMI2.opt+x$BMI3_betarev[j]*BMI3.opt+x$bp_betarev[j]*bp.opt+x$HDL_betarev[j]*HDL.opt+x$trig_betarev[j]*trig.opt+x$glucose_betarev[j]*gluc.opt
        
        risk.opt <- 1/(1+exp(-Zhatfinal.opt))
        
        riskc.opt <- risk.opt-x[j,"c"]
        
        #constraints (subject to:)
        
        if(age.s <= x$age.s[i] + z &&
           age.s >= x$age.s[i] - z &&
           sex.s <= x$sex.s[i] + z &&
           sex.s >= x$sex.s[i] - z &&
           BMI.s <= x$BMI.s[i] + z &&
           BMI.s >= x$BMI.s[i] - z &&
           HDL.s <= x$HDL.s[i] + z &&
           HDL.s >= x$HDL.s[i] - z &&
           trig.s <= x$trig.s[i] + z &&
           trig.s >= x$trig.s[i] - z &&
           gluc.s <= x$glu.s[i] + z &&
           gluc.s >= x$glu.s[i] - z &&
           bp1.s <= x$bp1.s[i] + z &&
           bp1.s >= x$bp1.s[i] - z &&
           bp2.s <= x$bp2.s[i] + z &&
           bp2.s >= x$bp2.s[i] - z &&
           bp3.s <= x$bp3.s[i] + z &&
           bp3.s >= x$bp3.s[i] - z &&
           hdiab.s <= x$hdiab.s[i] + z &&
           hdiab.s >= x$hdiab.s[i] - z &&
           (sqrt((x$age.s[i]-age.s)^2+(x$sex.s[i]-sex.s)^2+(x$BMI.s[i]-BMI.s)^2+(x$HDL.s[i]-HDL.s)^2+(x$trig.s[i]-trig.s)^2+(x$glu.s[i]-gluc.s)^2+(x$bp1.s[i]-bp1.s)^2+(x$bp2.s[i]-bp2.s)^2+(x$bp3.s[i]-bp3.s)^2+(x$hdiab.s[i]-hdiab.s)^2)) <= z
        ){riskc.opt}
      }
      
      #if final risk of patient is negative (positive) then maximize (minimize) optimization and save optimized value of risk after slight variations
      
      data$riskfinalopt[i] <- ifelse(data$riskfinal[i]>0, {optimx(par=c(
        age.s = data$age.s[i],
        sex.s = data$sex.s[i],
        BMI.s = data$BMI.s[i],
        HDL.s = data$HDL.s[i],
        trig.s = data$trig.s[i],
        gluc.s = data$glu.s[i],
        bp1.s = data$bp1.s[i],
        bp2.s = data$bp2.s[i],
        bp3.s = data$bp3.s[i],
        hdiab.s = data$hdiab.s[i]), ofopt, method = c("Nelder-Mead"), control=list(badval=NA))$value}, {optimx(par=c(age.s = data$age.s[i],
                                                                                                                     sex.s = data$sex.s[i],
                                                                                                                     BMI.s = data$BMI.s[i],
                                                                                                                     HDL.s = data$HDL.s[i],
                                                                                                                     trig.s = data$trig.s[i],
                                                                                                                     gluc.s = data$glu.s[i],
                                                                                                                     bp1.s = data$bp1.s[i],
                                                                                                                     bp2.s = data$bp2.s[i],
                                                                                                                     bp3.s = data$bp3.s[i],
                                                                                                                     hdiab.s = data$hdiab.s[i]), ofopt, method = c("Nelder-Mead"), control=list(maximize=TRUE, badval=NA))$value})
      
    }
    
    data$rand <- sign(data$riskfinal) != sign(data$riskfinalopt) #true means that patient changed signs
    #table(sign(data$riskfinal) != sign(data$riskfinalopt))
    #which(sign(data$riskfinal) != sign(data$riskfinalopt))
    
    return(data)
  }
  
  
  
  final2 <- function(data, j, z) {
    
      data$rand[is.na(data$rand)] <- 0
    
    for(i in 1:(j)) {
      ofopt <- function(par, x=data){
        
        #Extract guesses for standardized variables (slightly varied) par is just an example of a feasible solution.
        age.s <- par[1]
        sex.s <- par[2]
        BMI.s <- par[3]
        HDL.s <- par[4]
        trig.s <- par[5]
        gluc.s <- par[6]
        bp1.s <- par[7]
        bp2.s <- par[8]
        bp3.s <- par[9]
        hdiab.s <- par[10]
        
        
        #define raw variables based on optimized values (convert back standardized values to raw to be used inside log reg formula)
        
#age
        age1.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) < 50, 1, 0)
        age2.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) >= 50 & age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) < 65, 1, 0)
        age3.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) >= 65, 1, 0)
        #sex
        #sex.opt <- ifelse(sex.s*sd(x$RIAGENDR)+mean(x$RIAGENDR) >= 0.5, 1, 0)
        sex.opt <- min(max(sex.s*sd(x$RIAGENDR)+mean(x$RIAGENDR),0),1)
        #BMI
        BMI1.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) < 25, 1, 0)
        BMI2.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) >= 25 & BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) < 30, 1, 0)
        BMI3.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) >= 30, 1, 0)
        #HDL
        #HDL.opt <- ifelse((sex.opt == 1 & HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD)< 40) | (sex.opt == 0 & HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD) < 50), 1, 0)
        HDL.opt <- ifelse(HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD)< 40, 1, ifelse(HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD) >= 50, 0, (1-sex.opt)))
        #triglyceride
        trig.opt <- ifelse(trig.s*sd(x$LBXTR)+mean(x$LBXTR) >= 150, 1, 0)
        #fasting glucose
        gluc.opt <- ifelse(gluc.s*sd(x$LBXGLU)+mean(x$LBXGLU)>= 100, 1, 0)
        #blood pressure
        #bp3.opt <- ifelse(bp3.s*sd(x$BPQ050A)+mean(x$BPQ050A) >= 0.5, 1, 0) #bp treatment
        bp3.opt <-  min(max(bp3.s*sd(x$BPQ050A)+mean(x$BPQ050A),0),1)  #bp treatment
        #bp.opt <- ifelse(bp1.s*sd(x$BPXSY1)+mean(x$BPXSY1) >= 130 | bp2.s*sd(x$BPXDI1)+mean(x$BPXDI1) >=85 | bp3.opt == 1, 1, 0)
        bp.opt <- ifelse(bp1.s*sd(x$BPXSY1)+mean(x$BPXSY1) >= 130 | bp2.s*sd(x$BPXDI1)+mean(x$BPXDI1) >=85, 1, bp3.opt)
        #histofdiab
        hdiab.opt <- ifelse(hdiab.s*sd(x$DIQ175A)+mean(x$DIQ175A) >= 0.5, 1, 0)
        #hdiab.opt <- min(max(hdiab.s*sd(x$DIQ175A)+mean(x$DIQ175A),0),1)
        
        #Calculate new risk with slight variations
        
Zhatfinal.opt <- x$int_betarev[j]+x$age2_betarev[j]*age2.opt+x$age3_betarev[j]*age3.opt+x$RIAGENDR_betarev[j]*sex.opt+x$DIQ175A_betarev[j]*hdiab.opt+x$BMI2_betarev[j]*BMI2.opt+x$BMI3_betarev[j]*BMI3.opt+x$bp_betarev[j]*bp.opt+x$HDL_betarev[j]*HDL.opt+x$trig_betarev[j]*trig.opt+x$glucose_betarev[j]*gluc.opt
        
        risk.opt <- 1/(1+exp(-Zhatfinal.opt))
        
        riskc.opt <- risk.opt-x[j,"c"]
        
        #constraints (subject to:)
        
        if(age.s <= x$age.s[i] + z &&
           age.s >= x$age.s[i] - z &&
           sex.s <= x$sex.s[i] + z &&
           sex.s >= x$sex.s[i] - z &&
           BMI.s <= x$BMI.s[i] + z &&
           BMI.s >= x$BMI.s[i] - z &&
           HDL.s <= x$HDL.s[i] + z &&
           HDL.s >= x$HDL.s[i] - z &&
           trig.s <= x$trig.s[i] + z &&
           trig.s >= x$trig.s[i] - z &&
           gluc.s <= x$glu.s[i] + z &&
           gluc.s >= x$glu.s[i] - z &&
           bp1.s <= x$bp1.s[i] + z &&
           bp1.s >= x$bp1.s[i] - z &&
           bp2.s <= x$bp2.s[i] + z &&
           bp2.s >= x$bp2.s[i] - z &&
           bp3.s <= x$bp3.s[i] + z &&
           bp3.s >= x$bp3.s[i] - z &&
           hdiab.s <= x$hdiab.s[i] + z &&
           hdiab.s >= x$hdiab.s[i] - z &&
           (sqrt((x$age.s[i]-age.s)^2+(x$sex.s[i]-sex.s)^2+(x$BMI.s[i]-BMI.s)^2+(x$HDL.s[i]-HDL.s)^2+(x$trig.s[i]-trig.s)^2+(x$glu.s[i]-gluc.s)^2+(x$bp1.s[i]-bp1.s)^2+(x$bp2.s[i]-bp2.s)^2+(x$bp3.s[i]-bp3.s)^2+(x$hdiab.s[i]-hdiab.s)^2)) <= z
        ){riskc.opt}
        
      }
      
      #if final risk of patient is negative (positive) then maximize (minimize) optimization and save optimized value of risk after slight variations
    
  
      data$riskfinalopt2[i]<- ifelse(data$rand[i] == "TRUE", {data$riskfinalopt[i]}, {ifelse(data$riskfinal[i]>0, {optimx(par=c(
        age.s = data$age.s[i],
        sex.s = data$sex.s[i],
        BMI.s = data$BMI.s[i],
        HDL.s = data$HDL.s[i],
        trig.s = data$trig.s[i],
        gluc.s = data$glu.s[i],
        bp1.s = data$bp1.s[i],
        bp2.s = data$bp2.s[i],
        bp3.s = data$bp3.s[i],
        hdiab.s = data$hdiab.s[i]), ofopt, method = c("Nelder-Mead"), control=list(badval=NA))$value}, {optimx(par=c(age.s = data$age.s[i],
        sex.s = data$sex.s[i],
        BMI.s = data$BMI.s[i],
        HDL.s = data$HDL.s[i],
        trig.s = data$trig.s[i],
        gluc.s = data$glu.s[i],
        bp1.s = data$bp1.s[i],
        bp2.s = data$bp2.s[i],
        bp3.s = data$bp3.s[i],
        hdiab.s = data$hdiab.s[i]), ofopt, method = c("Nelder-Mead"), control=list(maximize=TRUE, badval=NA))$value})})
  
    } 

    data$rand <- sign(data$riskfinal) != sign(data$riskfinalopt2) #true means that patient changed signs
    #table(sign(data$riskfinal) != sign(data$riskfinalopt))
    #which(sign(data$riskfinal) != sign(data$riskfinalopt))
    
    return(data)
  }
  
  
result <- function(data
  ) {
    
    n <- tryCatch(table(data$rand)["TRUE"], error = function(e) return(NA))
    glm1 <- tryCatch(lm(Zrealfinal ~ Afinal + riskfinal + riskfinal:Afinal, data = data, subset = rand==TRUE), error = function(e) return(NA))
   EST <- tryCatch(coef(glm1)["Afinal"], error = function(e) return(NA))
    LB <- tryCatch(summary(glm1)$coefficients["Afinal",1]+qnorm(0.025)*summary(glm1)$coefficients["Afinal",2], error = function(e) return(NA))
    UB <- tryCatch(summary(glm1)$coefficients["Afinal",1]+qnorm(0.975)*summary(glm1)$coefficients["Afinal",2], error = function(e) return(NA))
    Error <- tryCatch(EST-(-0.2), error = function(e) return(NA))
    #Errorlog <- tryCatch(coef(glm1)["Afinal"]-log(0.5), error = function(e) return(NA))
    Coverage <- tryCatch(between(-0.2, LB, UB), error = function(e) return(NA))
    
    c(n, EST, LB, UB, Error, Coverage)
    
}

  p1500z0.5 <- future_lapply(p1500, final, j=1500, z=0.5)
  rm(p1500)
  p1500z0.5.r <- data.frame(t(sapply(p1500z0.5, result)))
  colnames(p1500z0.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  
  
  p1500z1 <- future_lapply(p1500z0.5, final2, j=1500, z=1)
  rm(p1500z0.5)
  p1500z1.r <- data.frame(t(sapply(p1500z1, result)))
  colnames(p1500z1.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  

  p1500z1.5 <- future_lapply(p1500z1, final2, j=1500, z=1.5)
  rm(p1500z1)
  p1500z1.5.r <- data.frame(t(sapply(p1500z1.5, result)))
  colnames(p1500z1.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  rm(p1500z1.5)
  

  
  
   p2500z0.5 <- future_lapply(p2500, final, j=2500, z=0.5)
  rm(p2500)
  p2500z0.5.r <- data.frame(t(sapply(p2500z0.5, result)))
  colnames(p2500z0.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  
  p2500z1 <- future_lapply(p2500z0.5, final2, j=2500, z=1)
  rm(p2500z0.5)
  p2500z1.r <- data.frame(t(sapply(p2500z1, result)))
  colnames(p2500z1.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  
  p2500z1.5 <- future_lapply(p2500z1, final2, j=2500, z=1.5)
  rm(p2500z1)
  p2500z1.5.r <- data.frame(t(sapply(p2500z1.5, result)))
  colnames(p2500z1.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  rm(p2500z1.5)
  
  
  
  
   p3500z0.5 <- future_lapply(p3500, final, j=3500, z=0.5)
  rm(p3500)
  p3500z0.5.r <- data.frame(t(sapply(p3500z0.5, result)))
  colnames(p3500z0.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  
  
  p3500z1 <- future_lapply(p3500z0.5, final2, j=3500, z=1)
  rm(p3500z0.5)
  p3500z1.r <- data.frame(t(sapply(p3500z1, result)))
  colnames(p3500z1.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  
  
  p3500z1.5 <- future_lapply(p3500z1, final2, j=3500, z=1.5)
  rm(p3500z1)
  p3500z1.5.r <- data.frame(t(sapply(p3500z1.5, result)))
  colnames(p3500z1.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  rm(p3500z1.5)
  
 
  
  
  #final output
  return(list(p1500z0.5.r, p2500z0.5.r, p3500z0.5.r, p1500z1.r, p2500z1.r, p3500z1.r, p1500z1.5.r, p2500z1.5.r, p3500z1.5.r))
  
}

```

#execute function
#Revision s=0.5

```{r}
plan(multisession, workers = 20)

start <- Sys.time()
rev.p.5s1 <- revcutp(reps=200, p=.5, s=.5)
print(Sys.time()-start)

names(rev.p.5s1) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rev.p.5s1, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rev.p.5s1_run1.xlsx", sheetName = names(rev.p.5s1), rowNames = FALSE)
rm(rev.p.5s1)

start <- Sys.time()
rev.p.5s1 <- revcutp(reps=200, p=.5, s=.5)
print(Sys.time()-start)

names(rev.p.5s1) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rev.p.5s1, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rev.p.5s1_run2.xlsx", sheetName = names(rev.p.5s1), rowNames = FALSE)
rm(rev.p.5s1)


start <- Sys.time()
rev.p.5s1 <- revcutp(reps=200, p=.5, s=.5)
print(Sys.time()-start)

names(rev.p.5s1) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rev.p.5s1, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rev.p.5s1_run3.xlsx", sheetName = names(rev.p.5s1), rowNames = FALSE)
rm(rev.p.5s1)


start <- Sys.time()
rev.p.5s1 <- revcutp(reps=200, p=.5, s=.5)
print(Sys.time()-start)

names(rev.p.5s1) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rev.p.5s1, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rev.p.5s1_run4.xlsx", sheetName = names(rev.p.5s1), rowNames = FALSE)
rm(rev.p.5s1)


start <- Sys.time()
rev.p.5s1 <- revcutp(reps=200, p=.5, s=.5)
print(Sys.time()-start)

names(rev.p.5s1) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rev.p.5s1, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rev.p.5s1_run5.xlsx", sheetName = names(rev.p.5s1), rowNames = FALSE)
rm(rev.p.5s1)


start <- Sys.time()
rev.p.5s1 <- revcutp(reps=200, p=.5, s=.5)
print(Sys.time()-start)

names(rev.p.5s1) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rev.p.5s1, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rev.p.5s1_run6.xlsx", sheetName = names(rev.p.5s1), rowNames = FALSE)
rm(rev.p.5s1)


start <- Sys.time()
rev.p.5s1 <- revcutp(reps=200, p=.5, s=.5)
print(Sys.time()-start)

names(rev.p.5s1) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rev.p.5s1, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rev.p.5s1_run7.xlsx", sheetName = names(rev.p.5s1), rowNames = FALSE)
rm(rev.p.5s1)


start <- Sys.time()
rev.p.5s1 <- revcutp(reps=200, p=.5, s=.5)
print(Sys.time()-start)

names(rev.p.5s1) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rev.p.5s1, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rev.p.5s1_run8.xlsx", sheetName = names(rev.p.5s1), rowNames = FALSE)
rm(rev.p.5s1)


start <- Sys.time()
rev.p.5s1 <- revcutp(reps=200, p=.5, s=.5)
print(Sys.time()-start)

names(rev.p.5s1) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rev.p.5s1, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rev.p.5s1_run9.xlsx", sheetName = names(rev.p.5s1), rowNames = FALSE)
rm(rev.p.5s1)


start <- Sys.time()
rev.p.5s1 <- revcutp(reps=200, p=.5, s=.5)
print(Sys.time()-start)

names(rev.p.5s1) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rev.p.5s1, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rev.p.5s1_run10.xlsx", sheetName = names(rev.p.5s1), rowNames = FALSE)
rm(rev.p.5s1)

```


```{r, include=FALSE}
start <- Sys.time()
rev.p.5s1 <- revcutp(reps=100, p=.5, s=1)
print(Sys.time()-start)

names(rev.p.5s1) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rev.p.5s1, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rev.p.5s1.xlsx", sheetName = names(rev.p.5s1), rowNames = FALSE)
rm(rev.p.5s1)

start <- Sys.time()
rev.p.5s.5 <- revcutp(reps=100, p=.5, s=.5)
print(Sys.time()-start)

names(rev.p.5s.5) <- c("p1500z0.5.r", "p2500z0.5.r", "p3500z0.5.r", "p1500z1.r", "p2500z1.r", "p3500z1.r", "p1500z1.5.r", "p2500z1.5.r", "p3500z1.5.r")
openxlsx::write.xlsx(rev.p.5s.5, file = "P:\\ED\\Analysis_Data\\Zayas-Caban_Patterson_Keeping_Patients\\R_runs\\rev.p.5s.5.xlsx", sheetName = names(rev.p.5s.5), rowNames = FALSE)
rm(rev.p.5s.5)
```


#Rev with cutoff fixed function:
```{r}
library(future.apply)
plan(multisession, workers = 20)

revcut <- function(reps=20, s= 0, c=.1) {
  
  datarecal <- list()
  for(k in 1:reps) {
    
    data <- dataraw[sample(c(1:nrow(dataraw)), size=3500, replace=TRUE),]
    
    
    data$id <- seq(1, nrow(data))
    
    data$s <- s #static risk pred model
    
    data$int_betarev <- 0
    data$age2_betarev <- 0
    data$age3_betarev <- 0
    data$RIAGENDR_betarev <- 0
    data$DIQ175A_betarev <- 0
    data$BMI2_betarev <- 0
    data$BMI3_betarev <- 0
    data$bp_betarev <- 0
    data$HDL_betarev <- 0
    data$trig_betarev <- 0
    data$glucose_betarev <- 0
    data$Zhatup <- data$Zhat
    data$riskup <- data$risk
    data$Aup <- data$A
    data$Zprobup <- data$Zprob
    data$Zrealup <- data$Zreal
    
    #fit a log reg and update linear predictor
    for(i in 200:(nrow(data)-1)) {
  
      #revise (fit a new regression model)
revise <- glm(Zrealup~age+RIAGENDR+DIQ175A+BMI+bp+HDL+trig+glucose, family = "binomial", data=data[1:i,], subset = Aup==0)

  #new models betas after shrinkage
#data$Zhatrev[i+1] <- predict(revise, newdata=data[i+1,])
data$int_betarev[i+1] <- (-5.517)+data$s[i+1]*(revise$coefficients[[1]]-(-5.517))
data$age2_betarev[i+1] <- (-0.018)+data$s[i+1]*(revise$coefficients[[2]]-(-0.018))
data$age3_betarev[i+1] <- (-0.081)+data$s[i+1]*(revise$coefficients[[3]]-(-0.081))
data$RIAGENDR_betarev[i+1] <- (-0.010)+data$s[i+1]*(revise$coefficients[[4]]-(-0.010))
data$DIQ175A_betarev[i+1] <- (0.565)+data$s[i+1]*(revise$coefficients[[5]]-(0.565))
data$BMI2_betarev[i+1] <- (0.301)+data$s[i+1]*(revise$coefficients[[6]]-(0.301))
data$BMI3_betarev[i+1] <- (0.92)+data$s[i+1]*(revise$coefficients[[7]]-(0.92))
data$bp_betarev[i+1] <- (0.498)+data$s[i+1]*(revise$coefficients[[8]]-(0.498))
data$HDL_betarev[i+1] <- (0.944)+data$s[i+1]*(revise$coefficients[[9]]-(0.944))
data$trig_betarev[i+1] <- (0.575)+data$s[i+1]*(revise$coefficients[[10]]-(0.575))
data$glucose_betarev[i+1] <- (1.980)+data$s[i+1]*(revise$coefficients[[11]]-(1.980))

data$Zhatup[i+1] <- data$int_betarev[i+1]+data$age2_betarev[i+1]*data$age2[i+1]+data$age3_betarev[i+1]*data$age3[i+1]+data$RIAGENDR_betarev[i+1]*data$RIAGENDR[i+1]+data$DIQ175A_betarev[i+1]*data$DIQ175A[i+1]+data$BMI2_betarev[i+1]*data$BMI2[i+1]+data$BMI3_betarev[i+1]*data$BMI3[i+1]+data$bp_betarev[i+1]*data$bp[i+1]+data$HDL_betarev[i+1]*data$HDL[i+1]+data$trig_betarev[i+1]*data$trig[i+1]+data$glucose_betarev[i+1]*data$glucose[i+1]
      
      data$riskup[i+1] <- (1/(1+exp(-data$Zhatup[i+1])))-c
      data$Aup[i+1] <- ifelse(data$riskup[i+1]>=0, 1, 0)
      data$Zprobup[i+1] <- (1/(1+exp(-(0.5*data$Zhatup[i+1]+0.5))))-.2*data$Aup[i+1]
        
      data$Zrealup[i+1] <- rbinom(n=1, size = 1, prob = data$Zprobup[i+1])
    }
    
    datarecal[[k]] <- data
    
  }
  
  
  ithpatient <- function(data, j){
    
    data$Zhatfinal <- data$int_betarev[j]+data$age2_betarev[j]*data$age2+data$age3_betarev[j]*data$age3+data$RIAGENDR_betarev[j]*data$RIAGENDR+data$DIQ175A_betarev[j] *data$DIQ175A+data$BMI2_betarev[j]*data$BMI2+data$BMI3_betarev[j] *data$BMI3+data$bp_betarev[j]*data$bp+data$HDL_betarev[j]*data$HDL+data$trig_betarev[j]*data$trig+data$glucose_betarev[j]*data$glucose
    data$riskfinal <- (1/(1+exp(-data$Zhatfinal)))-c
    data$Afinal <- ifelse(data$riskfinal>=0, 1, 0)
    data$Zprobfinal <- (1/(1+exp(-(0.5*data$Zhatfinal+0.5))))-.2*data$Afinal
    
    for(i in 1:(nrow(data))) {
      data$Zrealfinal[i] <- rbinom(n=1, size = 1, prob = data$Zprobfinal[i])
    }
    
    data <- data[1:j,]
    data$riskfinalopt <- 0
    
    return(data)
    
  }
  
  
  p1500 <- future_lapply(datarecal, ithpatient, j=1500, future.seed = TRUE)
  p2500 <- future_lapply(datarecal, ithpatient, j=2500, future.seed = TRUE)
  p3500 <- future_lapply(datarecal, ithpatient, j=3500, future.seed = TRUE)
  
  rm(datarecal)
  
  
  final <- function(data, j=500, z=0.5) {
    
    j=j
    z=z
    
    for(i in 1:(j)) {
      ofopt <- function(par, x=data){
        
        #Extract guesses for standardized variables (slightly varied) par is just an example of a feasible solution.
        age.s <- par[1]
        sex.s <- par[2]
        BMI.s <- par[3]
        HDL.s <- par[4]
        trig.s <- par[5]
        gluc.s <- par[6]
        bp1.s <- par[7]
        bp2.s <- par[8]
        bp3.s <- par[9]
        hdiab.s <- par[10]
        
        
        #define raw variables based on optimized values (convert back standardized values to raw to be used inside log reg formula)
        
        #age
        age1.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) < 50, 1, 0)
        age2.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) >= 50 & age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) < 65, 1, 0)
        age3.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) >= 65, 1, 0)
        #sex
        #sex.opt <- ifelse(sex.s*sd(x$RIAGENDR)+mean(x$RIAGENDR) >= 0.5, 1, 0)
        sex.opt <- min(max(sex.s*sd(x$RIAGENDR)+mean(x$RIAGENDR),0),1)
        #BMI
        BMI1.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) < 25, 1, 0)
        BMI2.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) >= 25 & BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) < 30, 1, 0)
        BMI3.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) >= 30, 1, 0)
        #HDL
        #HDL.opt <- ifelse((sex.opt == 1 & HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD)< 40) | (sex.opt == 0 & HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD) < 50), 1, 0)
        HDL.opt <- ifelse(HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD)< 40, 1, ifelse(HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD) >= 50, 0, (1-sex.opt)))
        #triglyceride
        trig.opt <- ifelse(trig.s*sd(x$LBXTR)+mean(x$LBXTR) >= 150, 1, 0)
        #fasting glucose
        gluc.opt <- ifelse(gluc.s*sd(x$LBXGLU)+mean(x$LBXGLU)>= 100, 1, 0)
        #blood pressure
        #bp3.opt <- ifelse(bp3.s*sd(x$BPQ050A)+mean(x$BPQ050A) >= 0.5, 1, 0) #bp treatment
        bp3.opt <-  min(max(bp3.s*sd(x$BPQ050A)+mean(x$BPQ050A),0),1)  #bp treatment
        #bp.opt <- ifelse(bp1.s*sd(x$BPXSY1)+mean(x$BPXSY1) >= 130 | bp2.s*sd(x$BPXDI1)+mean(x$BPXDI1) >=85 | bp3.opt == 1, 1, 0)
        bp.opt <- ifelse(bp1.s*sd(x$BPXSY1)+mean(x$BPXSY1) >= 130 | bp2.s*sd(x$BPXDI1)+mean(x$BPXDI1) >=85, 1, bp3.opt)
        #histofdiab
        hdiab.opt <- ifelse(hdiab.s*sd(x$DIQ175A)+mean(x$DIQ175A) >= 0.5, 1, 0)
        #hdiab.opt <- min(max(hdiab.s*sd(x$DIQ175A)+mean(x$DIQ175A),0),1)
        
        #Calculate new risk with slight variations

        
Zhatfinal.opt <- x$int_betarev[j]+x$age2_betarev[j]*age2.opt+x$age3_betarev[j]*age3.opt+x$RIAGENDR_betarev[j]*sex.opt+x$DIQ175A_betarev[j]*hdiab.opt+x$BMI2_betarev[j]*BMI2.opt+x$BMI3_betarev[j]*BMI3.opt+x$bp_betarev[j]*bp.opt+x$HDL_betarev[j]*HDL.opt+x$trig_betarev[j]*trig.opt+x$glucose_betarev[j]*gluc.opt
        
        risk.opt <- 1/(1+exp(-Zhatfinal.opt))
        
        riskc.opt <- risk.opt-c
        
        #constraints (subject to:)
        
        if(age.s <= x$age.s[i] + z &&
           age.s >= x$age.s[i] - z &&
           sex.s <= x$sex.s[i] + z &&
           sex.s >= x$sex.s[i] - z &&
           BMI.s <= x$BMI.s[i] + z &&
           BMI.s >= x$BMI.s[i] - z &&
           HDL.s <= x$HDL.s[i] + z &&
           HDL.s >= x$HDL.s[i] - z &&
           trig.s <= x$trig.s[i] + z &&
           trig.s >= x$trig.s[i] - z &&
           gluc.s <= x$glu.s[i] + z &&
           gluc.s >= x$glu.s[i] - z &&
           bp1.s <= x$bp1.s[i] + z &&
           bp1.s >= x$bp1.s[i] - z &&
           bp2.s <= x$bp2.s[i] + z &&
           bp2.s >= x$bp2.s[i] - z &&
           bp3.s <= x$bp3.s[i] + z &&
           bp3.s >= x$bp3.s[i] - z &&
           hdiab.s <= x$hdiab.s[i] + z &&
           hdiab.s >= x$hdiab.s[i] - z &&
           (sqrt((x$age.s[i]-age.s)^2+(x$sex.s[i]-sex.s)^2+(x$BMI.s[i]-BMI.s)^2+(x$HDL.s[i]-HDL.s)^2+(x$trig.s[i]-trig.s)^2+(x$glu.s[i]-gluc.s)^2+(x$bp1.s[i]-bp1.s)^2+(x$bp2.s[i]-bp2.s)^2+(x$bp3.s[i]-bp3.s)^2+(x$hdiab.s[i]-hdiab.s)^2)) <= z
        ){riskc.opt}
      }
      
      #if final risk of patient is negative (positive) then maximize (minimize) optimization and save optimized value of risk after slight variations
      
      data$riskfinalopt[i] <- ifelse(data$riskfinal[i]>0, {optimx(par=c(
        age.s = data$age.s[i],
        sex.s = data$sex.s[i],
        BMI.s = data$BMI.s[i],
        HDL.s = data$HDL.s[i],
        trig.s = data$trig.s[i],
        gluc.s = data$glu.s[i],
        bp1.s = data$bp1.s[i],
        bp2.s = data$bp2.s[i],
        bp3.s = data$bp3.s[i],
        hdiab.s = data$hdiab.s[i]), ofopt, method = c("Nelder-Mead"), control=list(badval=NA))$value}, {optimx(par=c(age.s = data$age.s[i],
                                                                                                                     sex.s = data$sex.s[i],
                                                                                                                     BMI.s = data$BMI.s[i],
                                                                                                                     HDL.s = data$HDL.s[i],
                                                                                                                     trig.s = data$trig.s[i],
                                                                                                                     gluc.s = data$glu.s[i],
                                                                                                                     bp1.s = data$bp1.s[i],
                                                                                                                     bp2.s = data$bp2.s[i],
                                                                                                                     bp3.s = data$bp3.s[i],
                                                                                                                     hdiab.s = data$hdiab.s[i]), ofopt, method = c("Nelder-Mead"), control=list(maximize=TRUE, badval=NA))$value})
      
    }
    
    data$rand <- sign(data$riskfinal) != sign(data$riskfinalopt) #true means that patient changed signs
    #table(sign(data$riskfinal) != sign(data$riskfinalopt))
    #which(sign(data$riskfinal) != sign(data$riskfinalopt))
    
    return(data)
  }
  
  
  
  final2 <- function(data, j, z) {
    
      data$rand[is.na(data$rand)] <- 0
    
    for(i in 1:(j)) {
      ofopt <- function(par, x=data){
        
        #Extract guesses for standardized variables (slightly varied) par is just an example of a feasible solution.
        age.s <- par[1]
        sex.s <- par[2]
        BMI.s <- par[3]
        HDL.s <- par[4]
        trig.s <- par[5]
        gluc.s <- par[6]
        bp1.s <- par[7]
        bp2.s <- par[8]
        bp3.s <- par[9]
        hdiab.s <- par[10]
        
        
        #define raw variables based on optimized values (convert back standardized values to raw to be used inside log reg formula)
        
#age
        age1.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) < 50, 1, 0)
        age2.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) >= 50 & age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) < 65, 1, 0)
        age3.opt <- ifelse(age.s*sd(x$RIDAGEYR)+mean(x$RIDAGEYR) >= 65, 1, 0)
        #sex
        #sex.opt <- ifelse(sex.s*sd(x$RIAGENDR)+mean(x$RIAGENDR) >= 0.5, 1, 0)
        sex.opt <- min(max(sex.s*sd(x$RIAGENDR)+mean(x$RIAGENDR),0),1)
        #BMI
        BMI1.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) < 25, 1, 0)
        BMI2.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) >= 25 & BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) < 30, 1, 0)
        BMI3.opt <- ifelse(BMI.s*sd(x$BMXBMI)+mean(x$BMXBMI) >= 30, 1, 0)
        #HDL
        #HDL.opt <- ifelse((sex.opt == 1 & HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD)< 40) | (sex.opt == 0 & HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD) < 50), 1, 0)
        HDL.opt <- ifelse(HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD)< 40, 1, ifelse(HDL.s*sd(x$LBDHDD)+mean(x$LBDHDD) >= 50, 0, (1-sex.opt)))
        #triglyceride
        trig.opt <- ifelse(trig.s*sd(x$LBXTR)+mean(x$LBXTR) >= 150, 1, 0)
        #fasting glucose
        gluc.opt <- ifelse(gluc.s*sd(x$LBXGLU)+mean(x$LBXGLU)>= 100, 1, 0)
        #blood pressure
        #bp3.opt <- ifelse(bp3.s*sd(x$BPQ050A)+mean(x$BPQ050A) >= 0.5, 1, 0) #bp treatment
        bp3.opt <-  min(max(bp3.s*sd(x$BPQ050A)+mean(x$BPQ050A),0),1)  #bp treatment
        #bp.opt <- ifelse(bp1.s*sd(x$BPXSY1)+mean(x$BPXSY1) >= 130 | bp2.s*sd(x$BPXDI1)+mean(x$BPXDI1) >=85 | bp3.opt == 1, 1, 0)
        bp.opt <- ifelse(bp1.s*sd(x$BPXSY1)+mean(x$BPXSY1) >= 130 | bp2.s*sd(x$BPXDI1)+mean(x$BPXDI1) >=85, 1, bp3.opt)
        #histofdiab
        hdiab.opt <- ifelse(hdiab.s*sd(x$DIQ175A)+mean(x$DIQ175A) >= 0.5, 1, 0)
        #hdiab.opt <- min(max(hdiab.s*sd(x$DIQ175A)+mean(x$DIQ175A),0),1)
        
        #Calculate new risk with slight variations
        
Zhatfinal.opt <- x$int_betarev[j]+x$age2_betarev[j]*age2.opt+x$age3_betarev[j]*age3.opt+x$RIAGENDR_betarev[j]*sex.opt+x$DIQ175A_betarev[j]*hdiab.opt+x$BMI2_betarev[j]*BMI2.opt+x$BMI3_betarev[j]*BMI3.opt+x$bp_betarev[j]*bp.opt+x$HDL_betarev[j]*HDL.opt+x$trig_betarev[j]*trig.opt+x$glucose_betarev[j]*gluc.opt
        
        risk.opt <- 1/(1+exp(-Zhatfinal.opt))
        
        riskc.opt <- risk.opt-c
        
        #constraints (subject to:)
        
        if(age.s <= x$age.s[i] + z &&
           age.s >= x$age.s[i] - z &&
           sex.s <= x$sex.s[i] + z &&
           sex.s >= x$sex.s[i] - z &&
           BMI.s <= x$BMI.s[i] + z &&
           BMI.s >= x$BMI.s[i] - z &&
           HDL.s <= x$HDL.s[i] + z &&
           HDL.s >= x$HDL.s[i] - z &&
           trig.s <= x$trig.s[i] + z &&
           trig.s >= x$trig.s[i] - z &&
           gluc.s <= x$glu.s[i] + z &&
           gluc.s >= x$glu.s[i] - z &&
           bp1.s <= x$bp1.s[i] + z &&
           bp1.s >= x$bp1.s[i] - z &&
           bp2.s <= x$bp2.s[i] + z &&
           bp2.s >= x$bp2.s[i] - z &&
           bp3.s <= x$bp3.s[i] + z &&
           bp3.s >= x$bp3.s[i] - z &&
           hdiab.s <= x$hdiab.s[i] + z &&
           hdiab.s >= x$hdiab.s[i] - z &&
           (sqrt((x$age.s[i]-age.s)^2+(x$sex.s[i]-sex.s)^2+(x$BMI.s[i]-BMI.s)^2+(x$HDL.s[i]-HDL.s)^2+(x$trig.s[i]-trig.s)^2+(x$glu.s[i]-gluc.s)^2+(x$bp1.s[i]-bp1.s)^2+(x$bp2.s[i]-bp2.s)^2+(x$bp3.s[i]-bp3.s)^2+(x$hdiab.s[i]-hdiab.s)^2)) <= z
        ){riskc.opt}
        
      }
      
      #if final risk of patient is negative (positive) then maximize (minimize) optimization and save optimized value of risk after slight variations
    
  
      data$riskfinalopt2[i]<- ifelse(data$rand[i] == "TRUE", {data$riskfinalopt[i]}, {ifelse(data$riskfinal[i]>0, {optimx(par=c(
        age.s = data$age.s[i],
        sex.s = data$sex.s[i],
        BMI.s = data$BMI.s[i],
        HDL.s = data$HDL.s[i],
        trig.s = data$trig.s[i],
        gluc.s = data$glu.s[i],
        bp1.s = data$bp1.s[i],
        bp2.s = data$bp2.s[i],
        bp3.s = data$bp3.s[i],
        hdiab.s = data$hdiab.s[i]), ofopt, method = c("Nelder-Mead"), control=list(badval=NA))$value}, {optimx(par=c(age.s = data$age.s[i],
        sex.s = data$sex.s[i],
        BMI.s = data$BMI.s[i],
        HDL.s = data$HDL.s[i],
        trig.s = data$trig.s[i],
        gluc.s = data$glu.s[i],
        bp1.s = data$bp1.s[i],
        bp2.s = data$bp2.s[i],
        bp3.s = data$bp3.s[i],
        hdiab.s = data$hdiab.s[i]), ofopt, method = c("Nelder-Mead"), control=list(maximize=TRUE, badval=NA))$value})})
  
    } 

    data$rand <- sign(data$riskfinal) != sign(data$riskfinalopt2) #true means that patient changed signs
    #table(sign(data$riskfinal) != sign(data$riskfinalopt))
    #which(sign(data$riskfinal) != sign(data$riskfinalopt))
    
    return(data)
  }
  
  
 result <- function(data
  ) {
    
    n <- tryCatch(table(data$rand)["TRUE"], error = function(e) return(NA))
    glm1 <- tryCatch(lm(Zrealfinal ~ Afinal + riskfinal + riskfinal:Afinal, data = data, subset = rand==TRUE), error = function(e) return(NA))
   EST <- tryCatch(coef(glm1)["Afinal"], error = function(e) return(NA))
    LB <- tryCatch(summary(glm1)$coefficients["Afinal",1]+qnorm(0.025)*summary(glm1)$coefficients["Afinal",2], error = function(e) return(NA))
    UB <- tryCatch(summary(glm1)$coefficients["Afinal",1]+qnorm(0.975)*summary(glm1)$coefficients["Afinal",2], error = function(e) return(NA))
    Error <- tryCatch(EST-(-0.2), error = function(e) return(NA))
    #Errorlog <- tryCatch(coef(glm1)["Afinal"]-log(0.5), error = function(e) return(NA))
    Coverage <- tryCatch(between(-0.2, LB, UB), error = function(e) return(NA))
    
    c(n, EST, LB, UB, Error, Coverage)
    
  }
 
  p1500z0.5 <- future_lapply(p1500, final, j=1500, z=0.5)
  rm(p1500)
  p1500z0.5.r <- data.frame(t(sapply(p1500z0.5, result)))
  colnames(p1500z0.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  
  
  p1500z1 <- future_lapply(p1500z0.5, final2, j=1500, z=1)
  rm(p1500z0.5)
  p1500z1.r <- data.frame(t(sapply(p1500z1, result)))
  colnames(p1500z1.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  

  p1500z1.5 <- future_lapply(p1500z1, final2, j=1500, z=1.5)
  rm(p1500z1)
  p1500z1.5.r <- data.frame(t(sapply(p1500z1.5, result)))
  colnames(p1500z1.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  rm(p1500z1.5)
  

  
   p2500z0.5 <- future_lapply(p2500, final, j=2500, z=0.5)
  rm(p2500)
  p2500z0.5.r <- data.frame(t(sapply(p2500z0.5, result)))
  colnames(p2500z0.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  
  p2500z1 <- future_lapply(p2500z0.5, final2, j=2500, z=1)
  rm(p2500z0.5)
  p2500z1.r <- data.frame(t(sapply(p2500z1, result)))
  colnames(p2500z1.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  
  p2500z1.5 <- future_lapply(p2500z1, final2, j=2500, z=1.5)
  rm(p2500z1)
  p2500z1.5.r <- data.frame(t(sapply(p2500z1.5, result)))
  colnames(p2500z1.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  rm(p2500z1.5)
  
  

  p3500z0.5 <- future_lapply(p3500, final, j=3500, z=0.5)
  rm(p3500)
  p3500z0.5.r <- data.frame(t(sapply(p3500z0.5, result)))
  colnames(p3500z0.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  
  
  p3500z1 <- future_lapply(p3500z0.5, final2, j=3500, z=1)
  rm(p3500z0.5)
  p3500z1.r <- data.frame(t(sapply(p3500z1, result)))
  colnames(p3500z1.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  
  
  p3500z1.5 <- future_lapply(p3500z1, final2, j=3500, z=1.5)
  rm(p3500z1)
  p3500z1.5.r <- data.frame(t(sapply(p3500z1.5, result)))
  colnames(p3500z1.5.r) <- c("n", "EST", "LB", "UB", "Error",  "Coverage")
  rm(p3500z1.5)
  
  
  
  #final output
  return(list(p1500z0.5.r, p2500z0.5.r, p3500z0.5.r, p1500z1.r, p2500z1.r, p3500z1.r, p1500z1.5.r, p2500z1.5.r, p3500z1.5.r))
  
}

```


